%w = (
  bellman_ford.cr
  bfs.cr
  binary_trie.cr
  bit_graph.cr
  bit_set.cr
  both_side_cs.cr
  cake.cr
    complex_polar.cr
    complex.cr
    convolution.cr
    coodinate_compress_liner.cr
    coodinate_compress_segment_tree.cr
    coordinate_compression.cr
    cumulative_sum_2d.cr
    cumulative_sum.cr
    dag_tsort.cr
    digit_dp.cr
    dijkstra.cr
    div_num.cr
    domino.cr
    doubling.cr
    etc
    ext_gcd.cr
    fenwick_tree.cr
    floor_sum.cr
    geography.cr
    grid.cr
    imos.cr
    int.cr
    lazy_segment_tree.cr
    lis.cr
    list_graph.cr
    log_num.cr
    matrix_graph.cr
    matrix.cr
    max_flow.cr
    memo.cr
    min_cost_flow.cr
    mod_int.cr
    mod_num.cr
    mod_pow.cr
    montmort.cr
    ntt_convolution.cr
    old
    permutation_group.cr
    prime_division.cr
    prime_pythagorean_triple_iterator.cr
    prime.cr
    priority_queue.cr
    problem.cr
    range_add_range_sum.cr
    range_set.cr
    rerooting.cr
    ro.cr
    rolling_hash.cr
    segment_sieve.cr
    segment_tree.cr
    segment.cr
    spec
    split_and_list.cr
    sqrt_decomposition.cr
    state.cr
    string_index.cr
    strongly_connected_components.cr
    test_helper.cr
    test_tree.cr
    treap_insert_erace.cr
    treap_merge_split.cr
    treap_range_sum.cr
    treap.cr
    tree_tsort.cr
    tree.cr
    trie.cr
    tsort.cr
    union_find_tree.cr
    weighted_graph.cr
    合計 336

  )