/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/tamura/.choosenim/toolchains/nim-0.13.0/lib -o /home/tamura/project/atcoder/src/nimcache/stdlib_sequtils.o /home/tamura/project/atcoder/src/nimcache/stdlib_sequtils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct TY122431 TY122431;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Slice88482 Slice88482;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Slice88482  {
NI a;
NI b;
};
struct TY122431 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY122431*, newseq_122434)(NI len);
N_NIMCALL(void, TMP335)(void* p, NI op);
static N_INLINE(Slice88482, HEX2EHEX2E_101424)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
extern TNimType NTI104; /* int */
TNimType NTI122431; /* seq[fin] */
extern TFrame* frameptr_19436;
N_NIMCALL(void, TMP335)(void* p, NI op) {
	TY122431* a;
	NI LOC1;
	a = (TY122431*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(Slice88482, HEX2EHEX2E_101424)(NI a, NI b) {
	Slice88482 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(270, "system.nim");
	result.a = a;
	nimln(271, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TY122431*, repeat_122424)(NI x, NI n) {
	TY122431* result;
	nimfr("repeat", "sequtils.nim")
	result = 0;
	nimln(75, "sequtils.nim");
	result = newseq_122434(n);
	{
		NI i_122476;
		Slice88482 HEX3Atmp_122478;
		i_122476 = 0;
		memset((void*)(&HEX3Atmp_122478), 0, sizeof(HEX3Atmp_122478));
		nimln(3548, "system.nim");
		nimln(3550, "system.nim");
		HEX3Atmp_122478 = HEX2EHEX2E_101424(((NI) 0), ((NI) (subInt(n, 1))));
		{
			NI x_122482;
			NI HEX3Atmp_122484;
			NI HEX3Atmp_122486;
			NI res_122488;
			x_122482 = 0;
			HEX3Atmp_122484 = 0;
			HEX3Atmp_122486 = 0;
			nimln(2026, "system.nim");
			HEX3Atmp_122484 = HEX3Atmp_122478.a;
			HEX3Atmp_122486 = HEX3Atmp_122478.b;
			nimln(1874, "system.nim");
			res_122488 = HEX3Atmp_122484;
			{
				nimln(1875, "system.nim");
				while (1) {
					NI TMP336;
					if (!(res_122488 <= HEX3Atmp_122486)) goto LA4;
					nimln(1876, "system.nim");
					x_122482 = res_122488;
					nimln(2026, "system.nim");
					i_122476 = x_122482;
					nimln(77, "sequtils.nim");
					if ((NU)(i_122476) >= (NU)(result->Sup.len)) raiseIndexError();
					result->data[i_122476] = x;
					nimln(1895, "system.nim");
					TMP336 = addInt(res_122488, ((NI) 1));
					res_122488 = (NI)(TMP336);
				} LA4: ;
			}
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void) {
	nimfr("sequtils", "sequtils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void) {
NTI122431.size = sizeof(TY122431*);
NTI122431.kind = 24;
NTI122431.base = (&NTI104);
NTI122431.flags = 2;
NTI122431.marker = TMP335;
}

