/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/tamura/.choosenim/toolchains/nim-0.13.0/lib -o /home/tamura/project/atcoder/src/nimcache/stdlib_times.o /home/tamura/project/atcoder/src/nimcache/stdlib_times.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <time.h>
#include <string.h>
#include <sys/select.h>
#include <sys/time.h>
typedef struct Timeinterval105806 Timeinterval105806;
typedef struct Timeinfo105804 Timeinfo105804;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY105888 TY105888;
typedef struct Slice88482 Slice88482;
typedef struct Valueerror3646 Valueerror3646;
typedef struct Exception Exception;
typedef struct Cell47905 Cell47905;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50214 Gcstat50214;
typedef struct TY109059 TY109059;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
struct  Timeinterval105806  {
NI milliseconds;
NI seconds;
NI minutes;
NI hours;
NI days;
NI months;
NI years;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Timeinfo105804  {
  TNimObject Sup;
NI second;
NI minute;
NI hour;
NI monthday;
NU8 month;
NI year;
NU8 weekday;
NI yearday;
NIM_BOOL isdst;
NimStringDesc* tzname;
NI timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY106452[7];
struct TY105888 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY106469[7];
typedef NimStringDesc* TY107826[7];
typedef NimStringDesc* TY107836[12];
struct  Slice88482  {
NI a;
NI b;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3646  {
  Exception Sup;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50214 stat;
};
struct TY109059 {
NI Field0;
NI Field1;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
N_NIMCALL(time_t, fromseconds_105853)(NI64 since1970);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(Timeinterval105806, initinterval_106005)(NI milliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(Timeinterval105806, HEX2B_106024)(Timeinterval105806* ti1, Timeinterval105806* ti2);
N_NIMCALL(Timeinterval105806, HEX2D_106037)(Timeinterval105806* ti1, Timeinterval105806* ti2);
N_NIMCALL(NIM_BOOL, isleapyear_106105)(NI year);
N_NIMCALL(NI, getdaysinmonth_106114)(NU8 month, NI year);
N_NIMCALL(NI, getdaysinyear_106121)(NI year);
static N_INLINE(void, HEX2DHEX3D_106156)(NF* x, NF y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, HEX2BHEX3D_106203)(NF* x, NF y);
N_NIMCALL(NF, toseconds_106127)(Timeinfo105804* a, Timeinterval105806* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NF, HEX2F_88438)(NI x, NI y);
N_NIMCALL(void, HEX2B_106313)(Timeinfo105804* a, Timeinterval105806* interval, Timeinfo105804* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_106320)(Timeinfo105804* a, Timeinterval105806* interval, Timeinfo105804* Result);
N_NIMCALL(NI, miliseconds_106329)(Timeinterval105806* t);
N_NIMCALL(void, milisecondsHEX3D_106333)(Timeinterval105806* t, NI milliseconds);
N_NIMCALL(void, tmtotimeinfo_106445)(struct tm* tm, NIM_BOOL local, Timeinfo105804* Result);
N_NIMCALL(void, gettzname_105886)(TY105888* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_106001)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_106462)(Timeinfo105804* t);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_106003)(void);
N_NIMCALL(time_t, gettime_105839)(void);
N_NIMCALL(void, getlocaltime_105841)(time_t t, Timeinfo105804* Result);
N_NIMCALL(void, getgmtime_105844)(time_t t, Timeinfo105804* Result);
N_NIMCALL(time_t, timeinfototime_105847)(Timeinfo105804* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_107212)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_105861)(Timeinfo105804* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_105864)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_107240)(time_t t);
N_NIMCALL(time_t, wintimetounixtime_107245)(NI64 t);
N_NIMCALL(time_t, fromseconds_105850)(NF since1970);
N_NIMCALL(NF, toseconds_105858)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_107819)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_107829)(NU8 m);
static N_INLINE(Timeinterval105806, milliseconds_107839)(NI ms);
static N_INLINE(Timeinterval105806, seconds_107846)(NI s);
static N_INLINE(Timeinterval105806, minutes_107851)(NI m);
static N_INLINE(Timeinterval105806, hours_107856)(NI h);
static N_INLINE(Timeinterval105806, days_107861)(NI d);
static N_INLINE(Timeinterval105806, months_107865)(NI m);
static N_INLINE(Timeinterval105806, years_107870)(NI y);
N_NIMCALL(void, HEX2BHEX3D_107874)(time_t* t, Timeinterval105806* ti);
N_NIMCALL(time_t, HEX2B_107879)(time_t t, Timeinterval105806* ti);
N_NIMCALL(void, HEX2DHEX3D_107884)(time_t* t, Timeinterval105806* ti);
N_NIMCALL(time_t, HEX2D_107889)(time_t t, Timeinterval105806* ti);
N_NIMCALL(void, formattoken_107894)(Timeinfo105804* info, NimStringDesc* token, NimStringDesc** buf);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_88475)(NimStringDesc* s, Slice88482 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_80210, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice88482, HEX2EHEX2E_101424)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
N_NIMCALL(void, insert_90001)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr);
static N_INLINE(void, rtladdzct_53401)(Cell47905* c);
N_NOINLINE(void, addzct_51817)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_108012)(Timeinfo105804* info, NimStringDesc* f);
N_NIMCALL(void, parsetoken_108059)(Timeinfo105804* info, NimStringDesc* token, NimStringDesc* value, NI* j);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s);
N_NIMCALL(void, parse_108960)(NimStringDesc* value, NimStringDesc* layout, Timeinfo105804* Result);
N_NIMCALL(NI, countleapyears_109038)(NI yearspan);
N_NIMCALL(NI, countdays_109045)(NI yearspan);
N_NIMCALL(NI, countyears_109050)(NI dayspan);
N_NIMCALL(TY109059, countyearsanddays_109056)(NI dayspan);
N_NIMCALL(NU8, getdayofweek_109076)(NI day, NI month, NI year);
N_NIMCALL(NU8, getdayofweekjulian_109091)(NI day, NI month, NI year);
N_NIMCALL(void, timetotimeinfo_109102)(time_t t, Timeinfo105804* Result);
N_NIMCALL(Timeinterval105806, timetotimeinterval_109160)(time_t t);
NIM_CONST TY106452 weekdays_106450 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
STRING_LITERAL(TMP166, "UTC", 3);
NIM_CONST TY106469 weekdays_106466 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP167, "", 0);
STRING_LITERAL(TMP168, "Monday", 6);
STRING_LITERAL(TMP169, "Tuesday", 7);
STRING_LITERAL(TMP170, "Wednesday", 9);
STRING_LITERAL(TMP171, "Thursday", 8);
STRING_LITERAL(TMP172, "Friday", 6);
STRING_LITERAL(TMP173, "Saturday", 8);
STRING_LITERAL(TMP174, "Sunday", 6);
NIM_CONST TY107826 lookup_107823 = {((NimStringDesc*) &TMP168),
((NimStringDesc*) &TMP169),
((NimStringDesc*) &TMP170),
((NimStringDesc*) &TMP171),
((NimStringDesc*) &TMP172),
((NimStringDesc*) &TMP173),
((NimStringDesc*) &TMP174)}
;
STRING_LITERAL(TMP175, "January", 7);
STRING_LITERAL(TMP176, "February", 8);
STRING_LITERAL(TMP177, "March", 5);
STRING_LITERAL(TMP178, "April", 5);
STRING_LITERAL(TMP179, "May", 3);
STRING_LITERAL(TMP180, "June", 4);
STRING_LITERAL(TMP181, "July", 4);
STRING_LITERAL(TMP182, "August", 6);
STRING_LITERAL(TMP183, "September", 9);
STRING_LITERAL(TMP184, "October", 7);
STRING_LITERAL(TMP185, "November", 8);
STRING_LITERAL(TMP186, "December", 8);
NIM_CONST TY107836 lookup_107833 = {((NimStringDesc*) &TMP175),
((NimStringDesc*) &TMP176),
((NimStringDesc*) &TMP177),
((NimStringDesc*) &TMP178),
((NimStringDesc*) &TMP179),
((NimStringDesc*) &TMP180),
((NimStringDesc*) &TMP181),
((NimStringDesc*) &TMP182),
((NimStringDesc*) &TMP183),
((NimStringDesc*) &TMP184),
((NimStringDesc*) &TMP185),
((NimStringDesc*) &TMP186)}
;
STRING_LITERAL(TMP187, "d", 1);
STRING_LITERAL(TMP188, "dd", 2);
STRING_LITERAL(TMP189, "ddd", 3);
STRING_LITERAL(TMP190, "dddd", 4);
STRING_LITERAL(TMP191, "h", 1);
STRING_LITERAL(TMP192, "hh", 2);
STRING_LITERAL(TMP193, "H", 1);
STRING_LITERAL(TMP194, "HH", 2);
STRING_LITERAL(TMP195, "m", 1);
STRING_LITERAL(TMP196, "mm", 2);
STRING_LITERAL(TMP197, "M", 1);
STRING_LITERAL(TMP198, "MM", 2);
STRING_LITERAL(TMP199, "MMM", 3);
STRING_LITERAL(TMP200, "MMMM", 4);
STRING_LITERAL(TMP201, "s", 1);
STRING_LITERAL(TMP202, "ss", 2);
STRING_LITERAL(TMP203, "t", 1);
STRING_LITERAL(TMP204, "tt", 2);
STRING_LITERAL(TMP205, "y", 1);
STRING_LITERAL(TMP206, "yy", 2);
STRING_LITERAL(TMP207, "yyy", 3);
STRING_LITERAL(TMP208, "yyyy", 4);
STRING_LITERAL(TMP209, "yyyyy", 5);
STRING_LITERAL(TMP210, "z", 1);
STRING_LITERAL(TMP211, "zz", 2);
STRING_LITERAL(TMP212, "zzz", 3);
STRING_LITERAL(TMP213, "ZZZ", 3);
STRING_LITERAL(TMP214, "0", 1);
STRING_LITERAL(TMP215, "PM", 2);
STRING_LITERAL(TMP216, "AM", 2);
STRING_LITERAL(TMP217, ":00", 3);
STRING_LITERAL(TMP218, "Invalid format string: ", 23);
STRING_LITERAL(TMP233, "sun", 3);
STRING_LITERAL(TMP234, "mon", 3);
STRING_LITERAL(TMP235, "tue", 3);
STRING_LITERAL(TMP236, "wed", 3);
STRING_LITERAL(TMP237, "thu", 3);
STRING_LITERAL(TMP238, "fri", 3);
STRING_LITERAL(TMP239, "sat", 3);
STRING_LITERAL(TMP240, "Couldn\'t parse day of week (ddd), got: ", 39);
STRING_LITERAL(TMP244, "sunday", 6);
STRING_LITERAL(TMP245, "monday", 6);
STRING_LITERAL(TMP246, "tuesday", 7);
STRING_LITERAL(TMP247, "wednesday", 9);
STRING_LITERAL(TMP248, "thursday", 8);
STRING_LITERAL(TMP249, "friday", 6);
STRING_LITERAL(TMP250, "saturday", 8);
STRING_LITERAL(TMP251, "Couldn\'t parse day of week (dddd), got: ", 40);
STRING_LITERAL(TMP252, "jan", 3);
STRING_LITERAL(TMP253, "feb", 3);
STRING_LITERAL(TMP254, "mar", 3);
STRING_LITERAL(TMP255, "apr", 3);
STRING_LITERAL(TMP256, "may", 3);
STRING_LITERAL(TMP257, "jun", 3);
STRING_LITERAL(TMP258, "jul", 3);
STRING_LITERAL(TMP259, "aug", 3);
STRING_LITERAL(TMP260, "sep", 3);
STRING_LITERAL(TMP261, "oct", 3);
STRING_LITERAL(TMP262, "nov", 3);
STRING_LITERAL(TMP263, "dec", 3);
STRING_LITERAL(TMP264, "Couldn\'t parse month (MMM), got: ", 33);
STRING_LITERAL(TMP265, "january", 7);
STRING_LITERAL(TMP266, "february", 8);
STRING_LITERAL(TMP267, "march", 5);
STRING_LITERAL(TMP268, "april", 5);
STRING_LITERAL(TMP269, "june", 4);
STRING_LITERAL(TMP270, "july", 4);
STRING_LITERAL(TMP271, "august", 6);
STRING_LITERAL(TMP272, "september", 9);
STRING_LITERAL(TMP273, "october", 7);
STRING_LITERAL(TMP274, "november", 8);
STRING_LITERAL(TMP275, "december", 8);
STRING_LITERAL(TMP276, "Couldn\'t parse month (MMMM), got: ", 34);
STRING_LITERAL(TMP277, "Couldn\'t parse timezone offset (z), got: ", 41);
STRING_LITERAL(TMP278, "Couldn\'t parse timezone offset (zz), got: ", 42);
STRING_LITERAL(TMP279, "Couldn\'t parse timezone offset (zzz), got: ", 43);
extern TFrame* frameptr_19436;
extern TNimType NTI3608; /* RootObj */
TNimType NTI105804; /* TimeInfo */
extern TNimType NTI104; /* int */
TNimType NTI105807; /* range 0..61(int) */
TNimType NTI105810; /* range 0..59(int) */
TNimType NTI105812; /* range 0..23(int) */
TNimType NTI105815; /* range 1..31(int) */
TNimType NTI105603; /* Month */
TNimType NTI105605; /* WeekDay */
TNimType NTI105821; /* range 0..365(int) */
extern TNimType NTI130; /* bool */
extern TNimType NTI138; /* string */
extern TNimType NTI24025; /* ref ValueError */
extern TNimType NTI3646; /* ValueError */
extern Gcheap50218 gch_50259;

N_NIMCALL(time_t, fromseconds_105853)(NI64 since1970) {
	time_t result;
	result = 0;
	result = fromseconds_105850(((NF) (since1970)));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == IL64(0));
	return result;
}

N_NIMCALL(Timeinterval105806, initinterval_106005)(NI milliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	Timeinterval105806 result;
	NI carryo;
	memset((void*)(&result), 0, sizeof(result));
	carryo = ((NI) 0);
	result.milliseconds = ((NI) ((NI)(milliseconds % ((NI) 1000))));
	carryo = (NI)(milliseconds / ((NI) 1000));
	result.seconds = ((NI) ((NI)((NI)(carryo + seconds) % ((NI) 60))));
	carryo = (NI)(seconds / ((NI) 60));
	result.minutes = ((NI) ((NI)((NI)(carryo + minutes) % ((NI) 60))));
	carryo = (NI)(minutes / ((NI) 60));
	result.hours = ((NI) ((NI)((NI)(carryo + hours) % ((NI) 24))));
	carryo = (NI)(hours / ((NI) 24));
	result.days = (NI)(carryo + days);
	carryo = ((NI) 0);
	result.months = ((NI) ((NI)(months % ((NI) 12))));
	carryo = (NI)(months / ((NI) 12));
	result.years = (NI)(carryo + years);
	return result;
}

N_NIMCALL(Timeinterval105806, HEX2B_106024)(Timeinterval105806* ti1, Timeinterval105806* ti2) {
	Timeinterval105806 result;
	NI carryo;
	memset((void*)(&result), 0, sizeof(result));
	carryo = ((NI) 0);
	result.milliseconds = ((NI) ((NI)((NI)((*ti1).milliseconds + (*ti2).milliseconds) % ((NI) 1000))));
	carryo = (NI)((NI)((*ti1).milliseconds + (*ti2).milliseconds) / ((NI) 1000));
	result.seconds = ((NI) ((NI)((NI)((NI)(carryo + (*ti1).seconds) + (*ti2).seconds) % ((NI) 60))));
	carryo = (NI)((NI)((*ti1).seconds + (*ti2).seconds) / ((NI) 60));
	result.minutes = ((NI) ((NI)((NI)((NI)(carryo + (*ti1).minutes) + (*ti2).minutes) % ((NI) 60))));
	carryo = (NI)((NI)((*ti1).minutes + (*ti2).minutes) / ((NI) 60));
	result.hours = ((NI) ((NI)((NI)((NI)(carryo + (*ti1).hours) + (*ti2).hours) % ((NI) 24))));
	carryo = (NI)((NI)((*ti1).hours + (*ti2).hours) / ((NI) 24));
	result.days = (NI)((NI)(carryo + (*ti1).days) + (*ti2).days);
	carryo = ((NI) 0);
	result.months = ((NI) ((NI)((NI)((*ti1).months + (*ti2).months) % ((NI) 12))));
	carryo = (NI)((NI)((*ti1).months + (*ti2).months) / ((NI) 12));
	result.years = (NI)((NI)(carryo + (*ti1).years) + (*ti2).years);
	return result;
}

N_NIMCALL(Timeinterval105806, HEX2D_106037)(Timeinterval105806* ti1, Timeinterval105806* ti2) {
	Timeinterval105806 result;
	memset((void*)(&result), 0, sizeof(result));
	result = (*ti1);
	result.milliseconds -= (*ti2).milliseconds;
	result.seconds -= (*ti2).seconds;
	result.minutes -= (*ti2).minutes;
	result.hours -= (*ti2).hours;
	result.days -= (*ti2).days;
	result.months -= (*ti2).months;
	result.years -= (*ti2).years;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_106105)(NI year) {
	NIM_BOOL result;
{	result = 0;
	{
		if (!(((NI) ((NI)(year % ((NI) 400)))) == ((NI) 0))) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI)(year % ((NI) 100)))) == ((NI) 0))) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI)(year % ((NI) 4)))) == ((NI) 0))) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getdaysinmonth_106114)(NU8 month, NI year) {
	NI result;
	result = 0;
	switch (month) {
	case ((NU8) 1):
	{
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = isleapyear_106105(year);
			if (!LOC4) goto LA5;
			result = ((NI) 29);
		}
		goto LA2;
		LA5: ;
		{
			result = ((NI) 28);
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		result = ((NI) 30);
	}
	break;
	default:
	{
		result = ((NI) 31);
	}
	break;
	}
	return result;
}

N_NIMCALL(NI, getdaysinyear_106121)(NI year) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	{
		NIM_BOOL LOC4;
		LOC4 = 0;
		LOC4 = isleapyear_106105(year);
		if (!LOC4) goto LA5;
		LOC1 = ((NI) 1);
	}
	goto LA2;
	LA5: ;
	{
		LOC1 = ((NI) 0);
	}
	LA2: ;
	result = (NI)(((NI) 365) + LOC1);
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(void, HEX2DHEX3D_106156)(NF* x, NF y) {
	nimfr("-=", "system.nim")
	nimln(3271, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_106203)(NF* x, NF y) {
	nimfr("+=", "system.nim")
	nimln(3266, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

static N_INLINE(NF, HEX2F_88438)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(3120, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_106127)(Timeinfo105804* a, Timeinterval105806* interval) {
	NF result;
	Timeinfo105804 anew;
	Timeinterval105806 newinterv;
	NU8 curmonth;
	NF LOC24;
	result = 0;
	memset((void*)(&anew), 0, sizeof(anew));
	anew.Sup.m_type = (&NTI105804);
	genericAssign((void*)(&anew), (void*)a, (&NTI105804));
	newinterv = (*interval);
	result = 0.0;
	newinterv.months += (NI)((*interval).years * ((NI) 12));
	curmonth = anew.month;
	{
		if (!(newinterv.months < ((NI) 0))) goto LA3;
		{
			NI mth_106154;
			NI HEX3Atmp_106293;
			NI res_106296;
			mth_106154 = 0;
			HEX3Atmp_106293 = 0;
			HEX3Atmp_106293 = (NI)(((NI) -1) * newinterv.months);
			res_106296 = HEX3Atmp_106293;
			{
				while (1) {
					NI LOC8;
					if (!(((NI) 1) <= res_106296)) goto LA7;
					mth_106154 = res_106296;
					LOC8 = 0;
					LOC8 = getdaysinmonth_106114(curmonth, anew.year);
					HEX2DHEX3D_106156((&result), ((NF) ((NI)((NI)((NI)(LOC8 * ((NI) 24)) * ((NI) 60)) * ((NI) 60)))));
					{
						if (!(curmonth == ((NU8) 0))) goto LA11;
						curmonth = ((NU8) 11);
						anew.year -= ((NI) 1);
					}
					goto LA9;
					LA11: ;
					{
						curmonth -= ((NI) 1);
					}
					LA9: ;
					res_106296 -= ((NI) 1);
				} LA7: ;
			}
		}
	}
	goto LA1;
	LA3: ;
	{
		{
			NI mth_106201;
			NI HEX3Atmp_106302;
			NI res_106305;
			mth_106201 = 0;
			HEX3Atmp_106302 = 0;
			HEX3Atmp_106302 = newinterv.months;
			res_106305 = ((NI) 1);
			{
				while (1) {
					NI LOC18;
					if (!(res_106305 <= HEX3Atmp_106302)) goto LA17;
					mth_106201 = res_106305;
					LOC18 = 0;
					LOC18 = getdaysinmonth_106114(curmonth, anew.year);
					HEX2BHEX3D_106203((&result), ((NF) ((NI)((NI)((NI)(LOC18 * ((NI) 24)) * ((NI) 60)) * ((NI) 60)))));
					{
						if (!(curmonth == ((NU8) 11))) goto LA21;
						curmonth = ((NU8) 0);
						anew.year += ((NI) 1);
					}
					goto LA19;
					LA21: ;
					{
						curmonth += ((NI) 1);
					}
					LA19: ;
					res_106305 += ((NI) 1);
				} LA17: ;
			}
		}
	}
	LA1: ;
	HEX2BHEX3D_106203((&result), ((NF) ((NI)((NI)((NI)(newinterv.days * ((NI) 24)) * ((NI) 60)) * ((NI) 60)))));
	HEX2BHEX3D_106203((&result), ((NF) ((NI)((NI)(newinterv.hours * ((NI) 60)) * ((NI) 60)))));
	HEX2BHEX3D_106203((&result), ((NF) ((NI)(newinterv.minutes * ((NI) 60)))));
	HEX2BHEX3D_106203((&result), ((NF) (newinterv.seconds)));
	LOC24 = 0;
	LOC24 = HEX2F_88438(newinterv.milliseconds, ((NI) 1000));
	HEX2BHEX3D_106203((&result), LOC24);
	return result;
}

N_NIMCALL(void, HEX2B_106313)(Timeinfo105804* a, Timeinterval105806* interval, Timeinfo105804* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	time_t LOC2;
	LOC1 = 0;
	LOC1 = timeinfototime_105847(a);
	t = toseconds_105858(LOC1);
	secs = toseconds_106127(a, interval);
	LOC2 = 0;
	LOC2 = fromseconds_105850(((NF)(t) + (NF)(secs)));
	genericReset((void*)Result, (&NTI105804));
	(*Result).Sup.m_type = (&NTI105804);
	getlocaltime_105841(LOC2, Result);
}

N_NIMCALL(void, HEX2D_106320)(Timeinfo105804* a, Timeinterval105806* interval, Timeinfo105804* Result) {
	NF t;
	time_t LOC1;
	Timeinterval105806 intval;
	NF secs;
	time_t LOC2;
	LOC1 = 0;
	LOC1 = timeinfototime_105847(a);
	t = toseconds_105858(LOC1);
	memset((void*)(&intval), 0, sizeof(intval));
	intval.milliseconds = ((NI64)-((*interval).milliseconds));
	intval.seconds = ((NI64)-((*interval).seconds));
	intval.minutes = ((NI64)-((*interval).minutes));
	intval.hours = ((NI64)-((*interval).hours));
	intval.days = ((NI64)-((*interval).days));
	intval.months = ((NI64)-((*interval).months));
	intval.years = ((NI64)-((*interval).years));
	secs = toseconds_106127(a, (&intval));
	LOC2 = 0;
	LOC2 = fromseconds_105850(((NF)(t) + (NF)(secs)));
	genericReset((void*)Result, (&NTI105804));
	(*Result).Sup.m_type = (&NTI105804);
	getlocaltime_105841(LOC2, Result);
}

N_NIMCALL(NI, miliseconds_106329)(Timeinterval105806* t) {
	NI result;
	result = 0;
	result = (*t).milliseconds;
	return result;
}

N_NIMCALL(void, milisecondsHEX3D_106333)(Timeinterval105806* t, NI milliseconds) {
	(*t).milliseconds = milliseconds;
}

N_NIMCALL(void, gettzname_105886)(TY105888* Result) {
{	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(((NI) 0))- 0]));
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(((NI) 1))- 0]));
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_106001)(void) {
	NI result;
{	result = 0;
	result = timezone;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_106445)(struct tm* tm, NIM_BOOL local, Timeinfo105804* Result) {
	Timeinfo105804 LOC1;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI105804);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI105804);
	LOC1.second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.month = ((NU8) ((*tm).tm_mon));
	LOC1.year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.weekday = weekdays_106450[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY105888 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_105886((&LOC10));
			LOC1.tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY105888 LOC12;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_105886((&LOC12));
			LOC1.tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.tzname = copyString(((NimStringDesc*) &TMP166));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.timezone = gettimezone_106001();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.timezone = ((NI) 0);
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI105804));
}

N_NIMCALL(struct tm, timeinfototm_106462)(Timeinfo105804* t) {
	struct tm result;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	result.tm_sec = ((int) ((*t).second));
	result.tm_min = ((int) ((*t).minute));
	result.tm_hour = ((int) ((*t).hour));
	result.tm_mday = ((int) ((*t).monthday));
	result.tm_mon = ((int) ((*t).month));
	result.tm_year = ((int) ((NI)((*t).year - ((NI) 1900))));
	result.tm_wday = ((int) (weekdays_106466[((*t).weekday)- 0]));
	result.tm_yday = ((int) ((*t).yearday));
	LOC1 = 0;
	{
		if (!(*t).isdst) goto LA4;
		LOC1 = ((NI) 1);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) 0);
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_106003)(void) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = (NI)(LOC1 / (NI)(CLOCKS_PER_SEC / ((NI) 1000)));
	return result;
}

N_NIMCALL(time_t, gettime_105839)(void) {
	time_t result;
{	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, getlocaltime_105841)(time_t t, Timeinfo105804* Result) {
	time_t a;
	struct tm* lt;
	a = t;
	lt = localtime((&a));
	genericReset((void*)Result, (&NTI105804));
	(*Result).Sup.m_type = (&NTI105804);
	tmtotimeinfo_106445((&(*lt)), NIM_TRUE, Result);
}

N_NIMCALL(void, getgmtime_105844)(time_t t, Timeinfo105804* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = gmtime((&a));
	genericReset((void*)Result, (&NTI105804));
	(*Result).Sup.m_type = (&NTI105804);
	tmtotimeinfo_106445((&(*LOC1)), NIM_FALSE, Result);
}

N_NIMCALL(time_t, timeinfototime_105847)(Timeinfo105804* timeinfo) {
	time_t result;
	Timeinfo105804 ctimeinfo;
	struct tm LOC1;
{	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI105804);
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI105804));
	LOC1 = timeinfototm_106462((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_107212)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP167));
	i = ((NI) 0);
	{
		while (1) {
			NIM_BOOL LOC3;
			NIM_BOOL LOC4;
			LOC3 = 0;
			LOC4 = 0;
			LOC4 = !(((NU8)(p[i]) == (NU8)(0)));
			if (!(LOC4)) goto LA5;
			LOC4 = !(((NU8)(p[i]) == (NU8)(10)));
			LA5: ;
			LOC3 = LOC4;
			if (!(LOC3)) goto LA6;
			LOC3 = !(((NU8)(p[i]) == (NU8)(13)));
			LA6: ;
			if (!LOC3) goto LA2;
			result = addChar(result, p[i]);
			i += ((NI) 1);
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_105861)(Timeinfo105804* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	result = 0;
	LOC1 = timeinfototm_106462(timeinfo);
	p = asctime((&LOC1));
	result = tostringtillnl_107212(p);
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_105864)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
{	result = 0;
	a = time;
	LOC1 = 0;
	LOC1 = ctime((&a));
	result = tostringtillnl_107212(LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_107240)(time_t t) {
	NI64 result;
	result = 0;
	result = (NI64)((NI64)(((NI64) (t)) * IL64(10000000)) + IL64(116444736000000000));
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_107245)(NI64 t) {
	time_t result;
	result = 0;
	result = ((time_t) ((NI64)((NI64)(t - IL64(116444736000000000)) / IL64(10000000))));
	return result;
}

N_NIMCALL(time_t, fromseconds_105850)(NF since1970) {
	time_t result;
	result = 0;
	result = ((time_t) (since1970));
	return result;
}

N_NIMCALL(NF, toseconds_105858)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	struct timeval a;
	result = 0;
	memset((void*)(&a), 0, sizeof(a));
	gettimeofday((&a), NIM_NIL);
	result = ((NF)(((double) (a.tv_sec))) + (NF)(((NF)(((double) (a.tv_usec))) * (NF)(9.9999999999999995e-07))));
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	Timeinfo105804 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI105804);
	LOC1 = 0;
	LOC1 = gettime_105839();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI105804);
	getlocaltime_105841(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(ti.year);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI)(((NI) (ti.month)) + ((NI) 1)))), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.monthday)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	Timeinfo105804 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI105804);
	LOC1 = 0;
	LOC1 = gettime_105839();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI105804);
	getlocaltime_105841(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.hour)), ((NI) 2));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.minute)), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.second)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_107819)(NU8 day) {
	NimStringDesc* result;
{	result = 0;
	result = copyString(lookup_107823[(day)- 0]);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_107829)(NU8 m) {
	NimStringDesc* result;
{	result = 0;
	result = copyString(lookup_107833[(m)- 0]);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(Timeinterval105806, milliseconds_107839)(NI ms) {
	Timeinterval105806 result;
	memset((void*)(&result), 0, sizeof(result));
	result = initinterval_106005(((NI) ((NI)(ms % ((NI) 1000)))), (NI)(ms / ((NI) 1000)), ((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0));
	return result;
}

static N_INLINE(Timeinterval105806, seconds_107846)(NI s) {
	Timeinterval105806 result;
	memset((void*)(&result), 0, sizeof(result));
	result = initinterval_106005(((NI) 0), ((NI) ((NI)(s % ((NI) 60)))), (NI)(s / ((NI) 60)), ((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0));
	return result;
}

static N_INLINE(Timeinterval105806, minutes_107851)(NI m) {
	Timeinterval105806 result;
	memset((void*)(&result), 0, sizeof(result));
	result = initinterval_106005(((NI) 0), ((NI) 0), ((NI) ((NI)(m % ((NI) 60)))), (NI)(m / ((NI) 60)), ((NI) 0), ((NI) 0), ((NI) 0));
	return result;
}

static N_INLINE(Timeinterval105806, hours_107856)(NI h) {
	Timeinterval105806 result;
	memset((void*)(&result), 0, sizeof(result));
	result = initinterval_106005(((NI) 0), ((NI) 0), ((NI) 0), ((NI) ((NI)(h % ((NI) 24)))), (NI)(h / ((NI) 24)), ((NI) 0), ((NI) 0));
	return result;
}

static N_INLINE(Timeinterval105806, days_107861)(NI d) {
	Timeinterval105806 result;
	memset((void*)(&result), 0, sizeof(result));
	result = initinterval_106005(((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0), d, ((NI) 0), ((NI) 0));
	return result;
}

static N_INLINE(Timeinterval105806, months_107865)(NI m) {
	Timeinterval105806 result;
	memset((void*)(&result), 0, sizeof(result));
	result = initinterval_106005(((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0), ((NI) ((NI)(m % ((NI) 12)))), (NI)(m / ((NI) 12)));
	return result;
}

static N_INLINE(Timeinterval105806, years_107870)(NI y) {
	Timeinterval105806 result;
	memset((void*)(&result), 0, sizeof(result));
	result = initinterval_106005(((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0), y);
	return result;
}

N_NIMCALL(void, HEX2BHEX3D_107874)(time_t* t, Timeinterval105806* ti) {
	Timeinfo105804 LOC1;
	Timeinfo105804 LOC2;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI105804);
	getlocaltime_105841((*t), (&LOC1));
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.Sup.m_type = (&NTI105804);
	HEX2B_106313((&LOC1), ti, (&LOC2));
	(*t) = timeinfototime_105847((&LOC2));
}

N_NIMCALL(time_t, HEX2B_107879)(time_t t, Timeinterval105806* ti) {
	time_t result;
	Timeinfo105804 LOC1;
	Timeinfo105804 LOC2;
	result = 0;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI105804);
	getlocaltime_105841(t, (&LOC1));
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.Sup.m_type = (&NTI105804);
	HEX2B_106313((&LOC1), ti, (&LOC2));
	result = timeinfototime_105847((&LOC2));
	return result;
}

N_NIMCALL(void, HEX2DHEX3D_107884)(time_t* t, Timeinterval105806* ti) {
	Timeinfo105804 LOC1;
	Timeinfo105804 LOC2;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI105804);
	getlocaltime_105841((*t), (&LOC1));
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.Sup.m_type = (&NTI105804);
	HEX2D_106320((&LOC1), ti, (&LOC2));
	(*t) = timeinfototime_105847((&LOC2));
}

N_NIMCALL(time_t, HEX2D_107889)(time_t t, Timeinterval105806* ti) {
	time_t result;
	Timeinfo105804 LOC1;
	Timeinfo105804 LOC2;
	result = 0;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI105804);
	getlocaltime_105841(t, (&LOC1));
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.Sup.m_type = (&NTI105804);
	HEX2D_106320((&LOC1), ti, (&LOC2));
	result = timeinfototime_105847((&LOC2));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_88475)(NimStringDesc* s, Slice88482 x) {
	NimStringDesc* result;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(3141, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice88482, HEX2EHEX2E_101424)(NI a, NI b) {
	Slice88482 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(270, "system.nim");
	result.a = a;
	nimln(271, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(Cell47905*, usrtocell_51840)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53401)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_51817((&gch_50259.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_51840(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_51840((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_53401(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_107894)(Timeinfo105804* info, NimStringDesc* token, NimStringDesc** buf) {
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP167))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP196))) goto LA10;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP187))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP204))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP213))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP205))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP191))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP197))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP198))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP202))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP206))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP199))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP212))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP190))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP203))) goto LA17;
break;
	case 20: 
if (eqStrings(token, ((NimStringDesc*) &TMP209))) goto LA23;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP188))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP195))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP201))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP211))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP193))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP194))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP200))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP207))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP210))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP189))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP192))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP208))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		{
			if (!(((NI) ((*info).monthday)) < ((NI) 10))) goto LA36;
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP214));
		}
		LA36: ;
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		Slice88482 LOC41;
		NimStringDesc* LOC42;
		LOC40 = 0;
		LOC40 = HEX24_107819((*info).weekday);
		LOC41 = HEX2EHEX2E_101424(((NI) 0), ((NI) 2));
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_88475(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		LOC44 = 0;
		LOC44 = HEX24_107819((*info).weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		LOC46 = 0;
		{
			if (!(((NI) 12) < ((NI) ((*info).hour)))) goto LA49;
			LOC46 = ((NI) ((NI)(((NI) ((*info).hour)) - ((NI) 12))));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		{
			if (!(((NI) 12) < ((NI) ((*info).hour)))) goto LA56;
			amerhour = ((NI) ((NI)(((NI) ((*info).hour)) - ((NI) 12))));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).hour));
		}
		LA54: ;
		{
			if (!(amerhour < ((NI) 10))) goto LA61;
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		{
			if (!(((NI) ((*info).hour)) < ((NI) 10))) goto LA69;
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		{
			if (!(((NI) ((*info).minute)) < ((NI) 10))) goto LA77;
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NimStringDesc* LOC81;
		LOC81 = 0;
		LOC81 = nimIntToStr((NI)(((NI) ((*info).month)) + ((NI) 1)));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NimStringDesc* LOC87;
		{
			if (!((*info).month < ((NU8) 9))) goto LA85;
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		LOC87 = 0;
		LOC87 = nimIntToStr((NI)(((NI) ((*info).month)) + ((NI) 1)));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		Slice88482 LOC90;
		NimStringDesc* LOC91;
		LOC89 = 0;
		LOC89 = HEX24_107829((*info).month);
		LOC90 = HEX2EHEX2E_101424(((NI) 0), ((NI) 2));
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_88475(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		LOC93 = 0;
		LOC93 = HEX24_107829((*info).month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		{
			if (!(((NI) ((*info).second)) < ((NI) 10))) goto LA99;
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		{
			if (!(((NI) 12) <= ((NI) ((*info).hour)))) goto LA105;
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		{
			if (!(((NI) 12) <= ((NI) ((*info).hour)))) goto LA111;
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP215));
		}
		goto LA109;
		LA111: ;
		{
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP216));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		Slice88482 LOC122;
		NimStringDesc* LOC123;
		LOC115 = 0;
		LOC115 = nimIntToStr((*info).year);
		fr = (NI)((LOC115 ? LOC115->Sup.len : 0) - ((NI) 1));
		{
			if (!(fr < ((NI) 0))) goto LA118;
			fr = ((NI) 0);
		}
		LA118: ;
		LOC120 = 0;
		LOC120 = nimIntToStr((*info).year);
		LOC121 = 0;
		LOC121 = nimIntToStr((*info).year);
		LOC122 = HEX2EHEX2E_101424(fr, (NI)((LOC121 ? LOC121->Sup.len : 0) - ((NI) 1)));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_88475(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		Slice88482 LOC132;
		LOC125 = 0;
		LOC125 = nimIntToStr((*info).year);
		fr = (NI)((LOC125 ? LOC125->Sup.len : 0) - ((NI) 2));
		{
			if (!(fr < ((NI) 0))) goto LA128;
			fr = ((NI) 0);
		}
		LA128: ;
		LOC130 = 0;
		LOC130 = nimIntToStr((*info).year);
		LOC131 = 0;
		LOC131 = nimIntToStr((*info).year);
		LOC132 = HEX2EHEX2E_101424(fr, (NI)((LOC131 ? LOC131->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_88475(LOC130, LOC132);
		{
			NimStringDesc* LOC137;
			NimStringDesc* LOC138;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 2)))) goto LA135;
			LOC137 = 0;
			LOC138 = 0;
			LOC138 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 2) - (fyear ? fyear->Sup.len : 0)))));
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		Slice88482 LOC147;
		LOC140 = 0;
		LOC140 = nimIntToStr((*info).year);
		fr = (NI)((LOC140 ? LOC140->Sup.len : 0) - ((NI) 3));
		{
			if (!(fr < ((NI) 0))) goto LA143;
			fr = ((NI) 0);
		}
		LA143: ;
		LOC145 = 0;
		LOC145 = nimIntToStr((*info).year);
		LOC146 = 0;
		LOC146 = nimIntToStr((*info).year);
		LOC147 = HEX2EHEX2E_101424(fr, (NI)((LOC146 ? LOC146->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_88475(LOC145, LOC147);
		{
			NimStringDesc* LOC152;
			NimStringDesc* LOC153;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 3)))) goto LA150;
			LOC152 = 0;
			LOC153 = 0;
			LOC153 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 3) - (fyear ? fyear->Sup.len : 0)))));
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		Slice88482 LOC162;
		LOC155 = 0;
		LOC155 = nimIntToStr((*info).year);
		fr = (NI)((LOC155 ? LOC155->Sup.len : 0) - ((NI) 4));
		{
			if (!(fr < ((NI) 0))) goto LA158;
			fr = ((NI) 0);
		}
		LA158: ;
		LOC160 = 0;
		LOC160 = nimIntToStr((*info).year);
		LOC161 = 0;
		LOC161 = nimIntToStr((*info).year);
		LOC162 = HEX2EHEX2E_101424(fr, (NI)((LOC161 ? LOC161->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_88475(LOC160, LOC162);
		{
			NimStringDesc* LOC167;
			NimStringDesc* LOC168;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 4)))) goto LA165;
			LOC167 = 0;
			LOC168 = 0;
			LOC168 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 4) - (fyear ? fyear->Sup.len : 0)))));
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		Slice88482 LOC177;
		LOC170 = 0;
		LOC170 = nimIntToStr((*info).year);
		fr = (NI)((LOC170 ? LOC170->Sup.len : 0) - ((NI) 5));
		{
			if (!(fr < ((NI) 0))) goto LA173;
			fr = ((NI) 0);
		}
		LA173: ;
		LOC175 = 0;
		LOC175 = nimIntToStr((*info).year);
		LOC176 = 0;
		LOC176 = nimIntToStr((*info).year);
		LOC177 = HEX2EHEX2E_101424(fr, (NI)((LOC176 ? LOC176->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_88475(LOC175, LOC177);
		{
			NimStringDesc* LOC182;
			NimStringDesc* LOC183;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 5)))) goto LA180;
			LOC182 = 0;
			LOC183 = 0;
			LOC183 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 5) - (fyear ? fyear->Sup.len : 0)))));
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NimStringDesc* LOC185;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NimStringDesc* LOC187;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			if (!((hrs > 0? (hrs) : -(hrs)) < ((NI) 10))) goto LA190;
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			{
				if (!(hrs < ((NI) 0))) goto LA196;
				LOC193 = ((NI) 1);
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = ((NI) 0);
			}
			LA194: ;
			atindex = (NI)(((*buf) ? (*buf)->Sup.len : 0) - (NI)((LOC192 ? LOC192->Sup.len : 0) - LOC193));
			insert_90001(buf, ((NimStringDesc*) &TMP214), ((NI) (atindex)));
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC200 = 0;
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP217));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			if (!((hrs > 0? (hrs) : -(hrs)) < ((NI) 10))) goto LA204;
			LOC206 = 0;
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP217));
			LOC208 = 0;
			{
				if (!(hrs < ((NI) 0))) goto LA211;
				LOC208 = ((NI) 1);
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = ((NI) 0);
			}
			LA209: ;
			atindex = (NI)(((*buf) ? (*buf)->Sup.len : 0) - (NI)((LOC206 ? LOC206->Sup.len : 0) - LOC208));
			insert_90001(buf, ((NimStringDesc*) &TMP214), ((NI) (atindex)));
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		(*buf) = resizeString((*buf), (*info).tzname->Sup.len + 0);
appendString((*buf), (*info).tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		Valueerror3646* e_107999;
		NimStringDesc* LOC217;
		e_107999 = 0;
		e_107999 = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
		(*e_107999).Sup.Sup.m_type = (&NTI3646);
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP218));
appendString(LOC217, token);
		asgnRefNoCycle((void**) (&(*e_107999).Sup.message), LOC217);
		raiseException((Exception*)e_107999, "ValueError");
	}
	LA30: ;
}

N_NIMCALL(NimStringDesc*, format_108012)(Timeinfo105804* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP167));
	i = ((NI) 0);
	currentf = copyString(((NimStringDesc*) &TMP167));
	{
		while (1) {
			switch (((NU8)(f->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				formattoken_107894(info, currentf, (&result));
				currentf = copyString(((NimStringDesc*) &TMP167));
				{
					if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA6;
					goto LA1;
				}
				LA6: ;
				{
					if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA10;
					i += ((NI) 1);
					{
						while (1) {
							NIM_BOOL LOC14;
							LOC14 = 0;
							LOC14 = !(((NU8)(f->data[i]) == (NU8)(39)));
							if (!(LOC14)) goto LA15;
							LOC14 = (i < (NI)((f ? f->Sup.len : 0) - ((NI) 1)));
							LA15: ;
							if (!LOC14) goto LA13;
							result = addChar(result, f->data[i]);
							i += ((NI) 1);
						} LA13: ;
					}
				}
				goto LA8;
				LA10: ;
				{
					result = addChar(result, f->data[i]);
				}
				LA8: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC20;
					LOC20 = 0;
					LOC20 = ((currentf ? currentf->Sup.len : 0) < ((NI) 1));
					if (LOC20) goto LA21;
					LOC20 = ((NU8)(currentf->data[(currentf ? (currentf->Sup.len-1) : -1)]) == (NU8)(f->data[i]));
					LA21: ;
					if (!LOC20) goto LA22;
					currentf = addChar(currentf, f->data[i]);
				}
				goto LA18;
				LA22: ;
				{
					formattoken_107894(info, currentf, (&result));
					i -= ((NI) 1);
					currentf = copyString(((NimStringDesc*) &TMP167));
				}
				LA18: ;
			}
			break;
			}
			i += ((NI) 1);
		}
	} LA1: ;
	return result;
}

N_NIMCALL(void, parsetoken_108059)(Timeinfo105804* info, NimStringDesc* token, NimStringDesc* value, NI* j) {
	NI sv;
	sv = 0;
	switch (hashString(token) & 31) {
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP196))) goto LA8;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP187))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP204))) goto LA16;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP213))) goto LA22;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP191))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP197))) goto LA9;
if (eqStrings(token, ((NimStringDesc*) &TMP198))) goto LA10;
if (eqStrings(token, ((NimStringDesc*) &TMP202))) goto LA14;
if (eqStrings(token, ((NimStringDesc*) &TMP206))) goto LA17;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP199))) goto LA11;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP212))) goto LA21;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP190))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP203))) goto LA15;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP188))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP195))) goto LA7;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP201))) goto LA13;
if (eqStrings(token, ((NimStringDesc*) &TMP211))) goto LA20;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP193))) goto LA5;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP194))) goto LA6;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP200))) goto LA12;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP210))) goto LA19;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP189))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP192))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP208))) goto LA18;
break;
	}
	goto LA23;
	LA1: ;
	{
		NI pd;
		Slice88482 LOC26;
		NimStringDesc* LOC27;
		LOC26 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC27 = 0;
		LOC27 = HEX5BHEX5D_88475(value, LOC26);
		pd = npuParseInt(LOC27, (&sv), ((NI) 0));
		(*info).monthday = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA2: ;
	{
		Slice88482 LOC29;
		NimStringDesc* LOC30;
		NI LOC31;
		LOC29 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC30 = 0;
		LOC30 = HEX5BHEX5D_88475(value, LOC29);
		LOC31 = 0;
		LOC31 = nsuParseInt(LOC30);
		(*info).monthday = ((NI) (LOC31));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA3: ;
	{
		Slice88482 LOC33;
		NimStringDesc* LOC34;
		NimStringDesc* LOC35;
		LOC33 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 2)));
		LOC34 = 0;
		LOC34 = HEX5BHEX5D_88475(value, LOC33);
		LOC35 = 0;
		LOC35 = nsuToLowerStr(LOC34);
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP233))) goto LA36;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP234))) goto LA37;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP235))) goto LA38;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP236))) goto LA39;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP237))) goto LA40;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP238))) goto LA41;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP239))) goto LA42;
		goto LA43;
		LA36: ;
		{
			(*info).weekday = ((NU8) 6);
		}
		goto LA44;
		LA37: ;
		{
			(*info).weekday = ((NU8) 0);
		}
		goto LA44;
		LA38: ;
		{
			(*info).weekday = ((NU8) 1);
		}
		goto LA44;
		LA39: ;
		{
			(*info).weekday = ((NU8) 2);
		}
		goto LA44;
		LA40: ;
		{
			(*info).weekday = ((NU8) 3);
		}
		goto LA44;
		LA41: ;
		{
			(*info).weekday = ((NU8) 4);
		}
		goto LA44;
		LA42: ;
		{
			(*info).weekday = ((NU8) 5);
		}
		goto LA44;
		LA43: ;
		{
			Valueerror3646* e_108131;
			NimStringDesc* LOC53;
			Slice88482 LOC54;
			NimStringDesc* LOC55;
			e_108131 = 0;
			e_108131 = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
			(*e_108131).Sup.Sup.m_type = (&NTI3646);
			LOC53 = 0;
			LOC54 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 2)));
			LOC55 = 0;
			LOC55 = HEX5BHEX5D_88475(value, LOC54);
			LOC53 = rawNewString(LOC55->Sup.len + 39);
appendString(LOC53, ((NimStringDesc*) &TMP240));
appendString(LOC53, LOC55);
			asgnRefNoCycle((void**) (&(*e_108131).Sup.message), LOC53);
			raiseException((Exception*)e_108131, "ValueError");
		}
		LA44: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA4: ;
	{
		{
			NIM_BOOL LOC59;
			Slice88482 LOC61;
			NimStringDesc* LOC62;
			NI LOC63;
			LOC59 = 0;
			LOC59 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC59)) goto LA60;
			LOC61 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 5)));
			LOC62 = 0;
			LOC62 = HEX5BHEX5D_88475(value, LOC61);
			LOC63 = 0;
			LOC63 = nsuCmpIgnoreCase(LOC62, ((NimStringDesc*) &TMP244));
			LOC59 = (LOC63 == ((NI) 0));
			LA60: ;
			if (!LOC59) goto LA64;
			(*info).weekday = ((NU8) 6);
			(*j) += ((NI) 6);
		}
		goto LA57;
		LA64: ;
		{
			NIM_BOOL LOC67;
			Slice88482 LOC69;
			NimStringDesc* LOC70;
			NI LOC71;
			LOC67 = 0;
			LOC67 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC67)) goto LA68;
			LOC69 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 5)));
			LOC70 = 0;
			LOC70 = HEX5BHEX5D_88475(value, LOC69);
			LOC71 = 0;
			LOC71 = nsuCmpIgnoreCase(LOC70, ((NimStringDesc*) &TMP245));
			LOC67 = (LOC71 == ((NI) 0));
			LA68: ;
			if (!LOC67) goto LA72;
			(*info).weekday = ((NU8) 0);
			(*j) += ((NI) 6);
		}
		goto LA57;
		LA72: ;
		{
			NIM_BOOL LOC75;
			Slice88482 LOC77;
			NimStringDesc* LOC78;
			NI LOC79;
			LOC75 = 0;
			LOC75 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC75)) goto LA76;
			LOC77 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 6)));
			LOC78 = 0;
			LOC78 = HEX5BHEX5D_88475(value, LOC77);
			LOC79 = 0;
			LOC79 = nsuCmpIgnoreCase(LOC78, ((NimStringDesc*) &TMP246));
			LOC75 = (LOC79 == ((NI) 0));
			LA76: ;
			if (!LOC75) goto LA80;
			(*info).weekday = ((NU8) 1);
			(*j) += ((NI) 7);
		}
		goto LA57;
		LA80: ;
		{
			NIM_BOOL LOC83;
			Slice88482 LOC85;
			NimStringDesc* LOC86;
			NI LOC87;
			LOC83 = 0;
			LOC83 = ((NI)((*j) + ((NI) 9)) <= (value ? value->Sup.len : 0));
			if (!(LOC83)) goto LA84;
			LOC85 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 8)));
			LOC86 = 0;
			LOC86 = HEX5BHEX5D_88475(value, LOC85);
			LOC87 = 0;
			LOC87 = nsuCmpIgnoreCase(LOC86, ((NimStringDesc*) &TMP247));
			LOC83 = (LOC87 == ((NI) 0));
			LA84: ;
			if (!LOC83) goto LA88;
			(*info).weekday = ((NU8) 2);
			(*j) += ((NI) 9);
		}
		goto LA57;
		LA88: ;
		{
			NIM_BOOL LOC91;
			Slice88482 LOC93;
			NimStringDesc* LOC94;
			NI LOC95;
			LOC91 = 0;
			LOC91 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC91)) goto LA92;
			LOC93 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 7)));
			LOC94 = 0;
			LOC94 = HEX5BHEX5D_88475(value, LOC93);
			LOC95 = 0;
			LOC95 = nsuCmpIgnoreCase(LOC94, ((NimStringDesc*) &TMP248));
			LOC91 = (LOC95 == ((NI) 0));
			LA92: ;
			if (!LOC91) goto LA96;
			(*info).weekday = ((NU8) 3);
			(*j) += ((NI) 8);
		}
		goto LA57;
		LA96: ;
		{
			NIM_BOOL LOC99;
			Slice88482 LOC101;
			NimStringDesc* LOC102;
			NI LOC103;
			LOC99 = 0;
			LOC99 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC99)) goto LA100;
			LOC101 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 5)));
			LOC102 = 0;
			LOC102 = HEX5BHEX5D_88475(value, LOC101);
			LOC103 = 0;
			LOC103 = nsuCmpIgnoreCase(LOC102, ((NimStringDesc*) &TMP249));
			LOC99 = (LOC103 == ((NI) 0));
			LA100: ;
			if (!LOC99) goto LA104;
			(*info).weekday = ((NU8) 4);
			(*j) += ((NI) 6);
		}
		goto LA57;
		LA104: ;
		{
			NIM_BOOL LOC107;
			Slice88482 LOC109;
			NimStringDesc* LOC110;
			NI LOC111;
			LOC107 = 0;
			LOC107 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC107)) goto LA108;
			LOC109 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 7)));
			LOC110 = 0;
			LOC110 = HEX5BHEX5D_88475(value, LOC109);
			LOC111 = 0;
			LOC111 = nsuCmpIgnoreCase(LOC110, ((NimStringDesc*) &TMP250));
			LOC107 = (LOC111 == ((NI) 0));
			LA108: ;
			if (!LOC107) goto LA112;
			(*info).weekday = ((NU8) 5);
			(*j) += ((NI) 8);
		}
		goto LA57;
		LA112: ;
		{
			Valueerror3646* e_108286;
			NimStringDesc* LOC115;
			e_108286 = 0;
			e_108286 = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
			(*e_108286).Sup.Sup.m_type = (&NTI3646);
			LOC115 = 0;
			LOC115 = rawNewString(value->Sup.len + 40);
appendString(LOC115, ((NimStringDesc*) &TMP251));
appendString(LOC115, value);
			asgnRefNoCycle((void**) (&(*e_108286).Sup.message), LOC115);
			raiseException((Exception*)e_108286, "ValueError");
		}
		LA57: ;
	}
	goto LA24;
	LA5: ;
	{
		NI pd;
		Slice88482 LOC117;
		NimStringDesc* LOC118;
		LOC117 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC118 = 0;
		LOC118 = HEX5BHEX5D_88475(value, LOC117);
		pd = npuParseInt(LOC118, (&sv), ((NI) 0));
		(*info).hour = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA6: ;
	{
		Slice88482 LOC120;
		NimStringDesc* LOC121;
		NI LOC122;
		LOC120 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC121 = 0;
		LOC121 = HEX5BHEX5D_88475(value, LOC120);
		LOC122 = 0;
		LOC122 = nsuParseInt(LOC121);
		(*info).hour = ((NI) (LOC122));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA7: ;
	{
		NI pd;
		Slice88482 LOC124;
		NimStringDesc* LOC125;
		LOC124 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC125 = 0;
		LOC125 = HEX5BHEX5D_88475(value, LOC124);
		pd = npuParseInt(LOC125, (&sv), ((NI) 0));
		(*info).minute = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA8: ;
	{
		Slice88482 LOC127;
		NimStringDesc* LOC128;
		NI LOC129;
		LOC127 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC128 = 0;
		LOC128 = HEX5BHEX5D_88475(value, LOC127);
		LOC129 = 0;
		LOC129 = nsuParseInt(LOC128);
		(*info).minute = ((NI) (LOC129));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA9: ;
	{
		NI pd;
		Slice88482 LOC131;
		NimStringDesc* LOC132;
		LOC131 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC132 = 0;
		LOC132 = HEX5BHEX5D_88475(value, LOC131);
		pd = npuParseInt(LOC132, (&sv), ((NI) 0));
		(*info).month = ((NU8) ((NI)(sv - ((NI) 1))));
		(*info).monthday = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA10: ;
	{
		NI month;
		Slice88482 LOC134;
		NimStringDesc* LOC135;
		LOC134 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC135 = 0;
		LOC135 = HEX5BHEX5D_88475(value, LOC134);
		month = nsuParseInt(LOC135);
		(*j) += ((NI) 2);
		(*info).month = ((NU8) ((NI)(month - ((NI) 1))));
	}
	goto LA24;
	LA11: ;
	{
		Slice88482 LOC137;
		NimStringDesc* LOC138;
		NimStringDesc* LOC139;
		LOC137 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 2)));
		LOC138 = 0;
		LOC138 = HEX5BHEX5D_88475(value, LOC137);
		LOC139 = 0;
		LOC139 = nsuToLowerStr(LOC138);
		switch (hashString(LOC139) & 15) {
		case 0: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP253))) goto LA141;
break;
		case 3: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP254))) goto LA142;
if (eqStrings(LOC139, ((NimStringDesc*) &TMP256))) goto LA144;
break;
		case 5: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP263))) goto LA151;
break;
		case 8: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP252))) goto LA140;
break;
		case 9: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP259))) goto LA147;
if (eqStrings(LOC139, ((NimStringDesc*) &TMP260))) goto LA148;
break;
		case 11: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP257))) goto LA145;
break;
		case 14: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP255))) goto LA143;
if (eqStrings(LOC139, ((NimStringDesc*) &TMP262))) goto LA150;
break;
		case 15: 
if (eqStrings(LOC139, ((NimStringDesc*) &TMP258))) goto LA146;
if (eqStrings(LOC139, ((NimStringDesc*) &TMP261))) goto LA149;
break;
		}
		goto LA152;
		LA140: ;
		{
			(*info).month = ((NU8) 0);
		}
		goto LA153;
		LA141: ;
		{
			(*info).month = ((NU8) 1);
		}
		goto LA153;
		LA142: ;
		{
			(*info).month = ((NU8) 2);
		}
		goto LA153;
		LA143: ;
		{
			(*info).month = ((NU8) 3);
		}
		goto LA153;
		LA144: ;
		{
			(*info).month = ((NU8) 4);
		}
		goto LA153;
		LA145: ;
		{
			(*info).month = ((NU8) 5);
		}
		goto LA153;
		LA146: ;
		{
			(*info).month = ((NU8) 6);
		}
		goto LA153;
		LA147: ;
		{
			(*info).month = ((NU8) 7);
		}
		goto LA153;
		LA148: ;
		{
			(*info).month = ((NU8) 8);
		}
		goto LA153;
		LA149: ;
		{
			(*info).month = ((NU8) 9);
		}
		goto LA153;
		LA150: ;
		{
			(*info).month = ((NU8) 10);
		}
		goto LA153;
		LA151: ;
		{
			(*info).month = ((NU8) 11);
		}
		goto LA153;
		LA152: ;
		{
			Valueerror3646* e_108430;
			NimStringDesc* LOC167;
			e_108430 = 0;
			e_108430 = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
			(*e_108430).Sup.Sup.m_type = (&NTI3646);
			LOC167 = 0;
			LOC167 = rawNewString(value->Sup.len + 33);
appendString(LOC167, ((NimStringDesc*) &TMP264));
appendString(LOC167, value);
			asgnRefNoCycle((void**) (&(*e_108430).Sup.message), LOC167);
			raiseException((Exception*)e_108430, "ValueError");
		}
		LA153: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA12: ;
	{
		{
			NIM_BOOL LOC171;
			Slice88482 LOC173;
			NimStringDesc* LOC174;
			NI LOC175;
			LOC171 = 0;
			LOC171 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC171)) goto LA172;
			LOC173 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 6)));
			LOC174 = 0;
			LOC174 = HEX5BHEX5D_88475(value, LOC173);
			LOC175 = 0;
			LOC175 = nsuCmpIgnoreCase(LOC174, ((NimStringDesc*) &TMP265));
			LOC171 = (LOC175 == ((NI) 0));
			LA172: ;
			if (!LOC171) goto LA176;
			(*info).month = ((NU8) 0);
			(*j) += ((NI) 7);
		}
		goto LA169;
		LA176: ;
		{
			NIM_BOOL LOC179;
			Slice88482 LOC181;
			NimStringDesc* LOC182;
			NI LOC183;
			LOC179 = 0;
			LOC179 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC179)) goto LA180;
			LOC181 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 7)));
			LOC182 = 0;
			LOC182 = HEX5BHEX5D_88475(value, LOC181);
			LOC183 = 0;
			LOC183 = nsuCmpIgnoreCase(LOC182, ((NimStringDesc*) &TMP266));
			LOC179 = (LOC183 == ((NI) 0));
			LA180: ;
			if (!LOC179) goto LA184;
			(*info).month = ((NU8) 1);
			(*j) += ((NI) 8);
		}
		goto LA169;
		LA184: ;
		{
			NIM_BOOL LOC187;
			Slice88482 LOC189;
			NimStringDesc* LOC190;
			NI LOC191;
			LOC187 = 0;
			LOC187 = ((NI)((*j) + ((NI) 5)) <= (value ? value->Sup.len : 0));
			if (!(LOC187)) goto LA188;
			LOC189 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 4)));
			LOC190 = 0;
			LOC190 = HEX5BHEX5D_88475(value, LOC189);
			LOC191 = 0;
			LOC191 = nsuCmpIgnoreCase(LOC190, ((NimStringDesc*) &TMP267));
			LOC187 = (LOC191 == ((NI) 0));
			LA188: ;
			if (!LOC187) goto LA192;
			(*info).month = ((NU8) 2);
			(*j) += ((NI) 5);
		}
		goto LA169;
		LA192: ;
		{
			NIM_BOOL LOC195;
			Slice88482 LOC197;
			NimStringDesc* LOC198;
			NI LOC199;
			LOC195 = 0;
			LOC195 = ((NI)((*j) + ((NI) 5)) <= (value ? value->Sup.len : 0));
			if (!(LOC195)) goto LA196;
			LOC197 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 4)));
			LOC198 = 0;
			LOC198 = HEX5BHEX5D_88475(value, LOC197);
			LOC199 = 0;
			LOC199 = nsuCmpIgnoreCase(LOC198, ((NimStringDesc*) &TMP268));
			LOC195 = (LOC199 == ((NI) 0));
			LA196: ;
			if (!LOC195) goto LA200;
			(*info).month = ((NU8) 3);
			(*j) += ((NI) 5);
		}
		goto LA169;
		LA200: ;
		{
			NIM_BOOL LOC203;
			Slice88482 LOC205;
			NimStringDesc* LOC206;
			NI LOC207;
			LOC203 = 0;
			LOC203 = ((NI)((*j) + ((NI) 3)) <= (value ? value->Sup.len : 0));
			if (!(LOC203)) goto LA204;
			LOC205 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 2)));
			LOC206 = 0;
			LOC206 = HEX5BHEX5D_88475(value, LOC205);
			LOC207 = 0;
			LOC207 = nsuCmpIgnoreCase(LOC206, ((NimStringDesc*) &TMP256));
			LOC203 = (LOC207 == ((NI) 0));
			LA204: ;
			if (!LOC203) goto LA208;
			(*info).month = ((NU8) 4);
			(*j) += ((NI) 3);
		}
		goto LA169;
		LA208: ;
		{
			NIM_BOOL LOC211;
			Slice88482 LOC213;
			NimStringDesc* LOC214;
			NI LOC215;
			LOC211 = 0;
			LOC211 = ((NI)((*j) + ((NI) 4)) <= (value ? value->Sup.len : 0));
			if (!(LOC211)) goto LA212;
			LOC213 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 3)));
			LOC214 = 0;
			LOC214 = HEX5BHEX5D_88475(value, LOC213);
			LOC215 = 0;
			LOC215 = nsuCmpIgnoreCase(LOC214, ((NimStringDesc*) &TMP269));
			LOC211 = (LOC215 == ((NI) 0));
			LA212: ;
			if (!LOC211) goto LA216;
			(*info).month = ((NU8) 5);
			(*j) += ((NI) 4);
		}
		goto LA169;
		LA216: ;
		{
			NIM_BOOL LOC219;
			Slice88482 LOC221;
			NimStringDesc* LOC222;
			NI LOC223;
			LOC219 = 0;
			LOC219 = ((NI)((*j) + ((NI) 4)) <= (value ? value->Sup.len : 0));
			if (!(LOC219)) goto LA220;
			LOC221 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 3)));
			LOC222 = 0;
			LOC222 = HEX5BHEX5D_88475(value, LOC221);
			LOC223 = 0;
			LOC223 = nsuCmpIgnoreCase(LOC222, ((NimStringDesc*) &TMP270));
			LOC219 = (LOC223 == ((NI) 0));
			LA220: ;
			if (!LOC219) goto LA224;
			(*info).month = ((NU8) 6);
			(*j) += ((NI) 4);
		}
		goto LA169;
		LA224: ;
		{
			NIM_BOOL LOC227;
			Slice88482 LOC229;
			NimStringDesc* LOC230;
			NI LOC231;
			LOC227 = 0;
			LOC227 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC227)) goto LA228;
			LOC229 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 5)));
			LOC230 = 0;
			LOC230 = HEX5BHEX5D_88475(value, LOC229);
			LOC231 = 0;
			LOC231 = nsuCmpIgnoreCase(LOC230, ((NimStringDesc*) &TMP271));
			LOC227 = (LOC231 == ((NI) 0));
			LA228: ;
			if (!LOC227) goto LA232;
			(*info).month = ((NU8) 7);
			(*j) += ((NI) 6);
		}
		goto LA169;
		LA232: ;
		{
			NIM_BOOL LOC235;
			Slice88482 LOC237;
			NimStringDesc* LOC238;
			NI LOC239;
			LOC235 = 0;
			LOC235 = ((NI)((*j) + ((NI) 9)) <= (value ? value->Sup.len : 0));
			if (!(LOC235)) goto LA236;
			LOC237 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 8)));
			LOC238 = 0;
			LOC238 = HEX5BHEX5D_88475(value, LOC237);
			LOC239 = 0;
			LOC239 = nsuCmpIgnoreCase(LOC238, ((NimStringDesc*) &TMP272));
			LOC235 = (LOC239 == ((NI) 0));
			LA236: ;
			if (!LOC235) goto LA240;
			(*info).month = ((NU8) 8);
			(*j) += ((NI) 9);
		}
		goto LA169;
		LA240: ;
		{
			NIM_BOOL LOC243;
			Slice88482 LOC245;
			NimStringDesc* LOC246;
			NI LOC247;
			LOC243 = 0;
			LOC243 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC243)) goto LA244;
			LOC245 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 6)));
			LOC246 = 0;
			LOC246 = HEX5BHEX5D_88475(value, LOC245);
			LOC247 = 0;
			LOC247 = nsuCmpIgnoreCase(LOC246, ((NimStringDesc*) &TMP273));
			LOC243 = (LOC247 == ((NI) 0));
			LA244: ;
			if (!LOC243) goto LA248;
			(*info).month = ((NU8) 9);
			(*j) += ((NI) 7);
		}
		goto LA169;
		LA248: ;
		{
			NIM_BOOL LOC251;
			Slice88482 LOC253;
			NimStringDesc* LOC254;
			NI LOC255;
			LOC251 = 0;
			LOC251 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC251)) goto LA252;
			LOC253 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 7)));
			LOC254 = 0;
			LOC254 = HEX5BHEX5D_88475(value, LOC253);
			LOC255 = 0;
			LOC255 = nsuCmpIgnoreCase(LOC254, ((NimStringDesc*) &TMP274));
			LOC251 = (LOC255 == ((NI) 0));
			LA252: ;
			if (!LOC251) goto LA256;
			(*info).month = ((NU8) 10);
			(*j) += ((NI) 8);
		}
		goto LA169;
		LA256: ;
		{
			NIM_BOOL LOC259;
			Slice88482 LOC261;
			NimStringDesc* LOC262;
			NI LOC263;
			LOC259 = 0;
			LOC259 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC259)) goto LA260;
			LOC261 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 7)));
			LOC262 = 0;
			LOC262 = HEX5BHEX5D_88475(value, LOC261);
			LOC263 = 0;
			LOC263 = nsuCmpIgnoreCase(LOC262, ((NimStringDesc*) &TMP275));
			LOC259 = (LOC263 == ((NI) 0));
			LA260: ;
			if (!LOC259) goto LA264;
			(*info).month = ((NU8) 11);
			(*j) += ((NI) 8);
		}
		goto LA169;
		LA264: ;
		{
			Valueerror3646* e_108680;
			NimStringDesc* LOC267;
			e_108680 = 0;
			e_108680 = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
			(*e_108680).Sup.Sup.m_type = (&NTI3646);
			LOC267 = 0;
			LOC267 = rawNewString(value->Sup.len + 34);
appendString(LOC267, ((NimStringDesc*) &TMP276));
appendString(LOC267, value);
			asgnRefNoCycle((void**) (&(*e_108680).Sup.message), LOC267);
			raiseException((Exception*)e_108680, "ValueError");
		}
		LA169: ;
	}
	goto LA24;
	LA13: ;
	{
		NI pd;
		Slice88482 LOC269;
		NimStringDesc* LOC270;
		LOC269 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC270 = 0;
		LOC270 = HEX5BHEX5D_88475(value, LOC269);
		pd = npuParseInt(LOC270, (&sv), ((NI) 0));
		(*info).second = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA14: ;
	{
		Slice88482 LOC272;
		NimStringDesc* LOC273;
		NI LOC274;
		LOC272 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC273 = 0;
		LOC273 = HEX5BHEX5D_88475(value, LOC272);
		LOC274 = 0;
		LOC274 = nsuParseInt(LOC273);
		(*info).second = ((NI) (LOC274));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA15: ;
	{
		{
			NIM_BOOL LOC278;
			NIM_BOOL LOC279;
			LOC278 = 0;
			LOC279 = 0;
			LOC279 = ((NU8)(value->data[(*j)]) == (NU8)(80));
			if (!(LOC279)) goto LA280;
			LOC279 = (((NI) 0) < ((NI) ((*info).hour)));
			LA280: ;
			LOC278 = LOC279;
			if (!(LOC278)) goto LA281;
			LOC278 = (((NI) ((*info).hour)) < ((NI) 12));
			LA281: ;
			if (!LOC278) goto LA282;
			(*info).hour += ((NI) 12);
		}
		LA282: ;
		(*j) += ((NI) 1);
	}
	goto LA24;
	LA16: ;
	{
		{
			NIM_BOOL LOC287;
			NIM_BOOL LOC288;
			Slice88482 LOC289;
			NimStringDesc* LOC290;
			LOC287 = 0;
			LOC288 = 0;
			LOC289 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
			LOC290 = 0;
			LOC290 = HEX5BHEX5D_88475(value, LOC289);
			LOC288 = eqStrings(LOC290, ((NimStringDesc*) &TMP215));
			if (!(LOC288)) goto LA291;
			LOC288 = (((NI) 0) < ((NI) ((*info).hour)));
			LA291: ;
			LOC287 = LOC288;
			if (!(LOC287)) goto LA292;
			LOC287 = (((NI) ((*info).hour)) < ((NI) 12));
			LA292: ;
			if (!LOC287) goto LA293;
			(*info).hour += ((NI) 12);
		}
		LA293: ;
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA17: ;
	{
		NI year;
		Slice88482 LOC296;
		NimStringDesc* LOC297;
		NI thiscen;
		time_t LOC298;
		Timeinfo105804 LOC299;
		LOC296 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 1)));
		LOC297 = 0;
		LOC297 = HEX5BHEX5D_88475(value, LOC296);
		year = nsuParseInt(LOC297);
		LOC298 = 0;
		LOC298 = gettime_105839();
		memset((void*)(&LOC299), 0, sizeof(LOC299));
		LOC299.Sup.m_type = (&NTI105804);
		getlocaltime_105841(LOC298, (&LOC299));
		thiscen = (NI)(LOC299.year / ((NI) 100));
		(*info).year = (NI)((NI)(thiscen * ((NI) 100)) + year);
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA18: ;
	{
		Slice88482 LOC301;
		NimStringDesc* LOC302;
		LOC301 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 3)));
		LOC302 = 0;
		LOC302 = HEX5BHEX5D_88475(value, LOC301);
		(*info).year = nsuParseInt(LOC302);
		(*j) += ((NI) 4);
	}
	goto LA24;
	LA19: ;
	{
		{
			NimStringDesc* LOC308;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA306;
			LOC308 = 0;
			LOC308 = nimCharToStr(value->data[(NI)((*j) + ((NI) 1))]);
			(*info).timezone = nsuParseInt(LOC308);
		}
		goto LA304;
		LA306: ;
		{
			NimStringDesc* LOC312;
			NI LOC313;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA310;
			LOC312 = 0;
			LOC312 = nimCharToStr(value->data[(NI)((*j) + ((NI) 1))]);
			LOC313 = 0;
			LOC313 = nsuParseInt(LOC312);
			(*info).timezone = (NI)(((NI) 0) - LOC313);
		}
		goto LA304;
		LA310: ;
		{
			Valueerror3646* e_108821;
			NimStringDesc* LOC315;
			e_108821 = 0;
			e_108821 = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
			(*e_108821).Sup.Sup.m_type = (&NTI3646);
			LOC315 = 0;
			LOC315 = rawNewString(42);
appendString(LOC315, ((NimStringDesc*) &TMP277));
appendChar(LOC315, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_108821).Sup.message), LOC315);
			raiseException((Exception*)e_108821, "ValueError");
		}
		LA304: ;
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA20: ;
	{
		{
			Slice88482 LOC321;
			NimStringDesc* LOC322;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA319;
			LOC321 = HEX2EHEX2E_101424((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC322 = 0;
			LOC322 = HEX5BHEX5D_88475(value, LOC321);
			(*info).timezone = nsuParseInt(LOC322);
		}
		goto LA317;
		LA319: ;
		{
			Slice88482 LOC326;
			NimStringDesc* LOC327;
			NI LOC328;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA324;
			LOC326 = HEX2EHEX2E_101424((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC327 = 0;
			LOC327 = HEX5BHEX5D_88475(value, LOC326);
			LOC328 = 0;
			LOC328 = nsuParseInt(LOC327);
			(*info).timezone = (NI)(((NI) 0) - LOC328);
		}
		goto LA317;
		LA324: ;
		{
			Valueerror3646* e_108863;
			NimStringDesc* LOC330;
			e_108863 = 0;
			e_108863 = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
			(*e_108863).Sup.Sup.m_type = (&NTI3646);
			LOC330 = 0;
			LOC330 = rawNewString(43);
appendString(LOC330, ((NimStringDesc*) &TMP278));
appendChar(LOC330, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_108863).Sup.message), LOC330);
			raiseException((Exception*)e_108863, "ValueError");
		}
		LA317: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA21: ;
	{
		{
			Slice88482 LOC336;
			NimStringDesc* LOC337;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA334;
			LOC336 = HEX2EHEX2E_101424((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC337 = 0;
			LOC337 = HEX5BHEX5D_88475(value, LOC336);
			(*info).timezone = nsuParseInt(LOC337);
		}
		goto LA332;
		LA334: ;
		{
			Slice88482 LOC341;
			NimStringDesc* LOC342;
			NI LOC343;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA339;
			LOC341 = HEX2EHEX2E_101424((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC342 = 0;
			LOC342 = HEX5BHEX5D_88475(value, LOC341);
			LOC343 = 0;
			LOC343 = nsuParseInt(LOC342);
			(*info).timezone = (NI)(((NI) 0) - LOC343);
		}
		goto LA332;
		LA339: ;
		{
			Valueerror3646* e_108905;
			NimStringDesc* LOC345;
			e_108905 = 0;
			e_108905 = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
			(*e_108905).Sup.Sup.m_type = (&NTI3646);
			LOC345 = 0;
			LOC345 = rawNewString(44);
appendString(LOC345, ((NimStringDesc*) &TMP279));
appendChar(LOC345, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_108905).Sup.message), LOC345);
			raiseException((Exception*)e_108905, "ValueError");
		}
		LA332: ;
		(*j) += ((NI) 6);
	}
	goto LA24;
	LA22: ;
	{
		Slice88482 LOC347;
		NimStringDesc* LOC348;
		LOC347 = HEX2EHEX2E_101424((*j), (NI)((*j) + ((NI) 2)));
		LOC348 = 0;
		LOC348 = HEX5BHEX5D_88475(value, LOC347);
		unsureAsgnRef((void**) (&(*info).tzname), nsuToUpperStr(LOC348));
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA23: ;
	{
		(*j) += (token ? token->Sup.len : 0);
	}
	LA24: ;
}

N_NIMCALL(void, parse_108960)(NimStringDesc* value, NimStringDesc* layout, Timeinfo105804* Result) {
	NI i;
	NI j;
	NimStringDesc* token;
	Timeinfo105804 info;
	time_t LOC1;
	time_t LOC30;
	Timeinfo105804 LOC31;
{	i = ((NI) 0);
	j = ((NI) 0);
	token = copyString(((NimStringDesc*) &TMP167));
	memset((void*)(&info), 0, sizeof(info));
	info.Sup.m_type = (&NTI105804);
	LOC1 = 0;
	LOC1 = gettime_105839();
	memset((void*)(&info), 0, sizeof(info));
	info.Sup.m_type = (&NTI105804);
	getlocaltime_105841(LOC1, (&info));
	info.hour = ((NI) 0);
	info.minute = ((NI) 0);
	info.second = ((NI) 0);
	{
		while (1) {
			switch (((NU8)(layout->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				{
					if (!(((NI) 0) < (token ? token->Sup.len : 0))) goto LA7;
					parsetoken_108059((&info), token, value, (&j));
				}
				LA7: ;
				token = copyString(((NimStringDesc*) &TMP167));
				{
					if (!((NU8)(layout->data[i]) == (NU8)(0))) goto LA11;
					goto LA2;
				}
				LA11: ;
				{
					if (!((NU8)(layout->data[i]) == (NU8)(39))) goto LA15;
					i += ((NI) 1);
					{
						while (1) {
							NIM_BOOL LOC19;
							LOC19 = 0;
							LOC19 = !(((NU8)(layout->data[i]) == (NU8)(39)));
							if (!(LOC19)) goto LA20;
							LOC19 = (i < (NI)((layout ? layout->Sup.len : 0) - ((NI) 1)));
							LA20: ;
							if (!LOC19) goto LA18;
							i += ((NI) 1);
							j += ((NI) 1);
						} LA18: ;
					}
					i += ((NI) 1);
				}
				goto LA13;
				LA15: ;
				{
					i += ((NI) 1);
					j += ((NI) 1);
				}
				LA13: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC25;
					LOC25 = 0;
					LOC25 = ((token ? token->Sup.len : 0) < ((NI) 1));
					if (LOC25) goto LA26;
					LOC25 = ((NU8)(token->data[(token ? (token->Sup.len-1) : -1)]) == (NU8)(layout->data[i]));
					LA26: ;
					if (!LOC25) goto LA27;
					token = addChar(token, layout->data[i]);
					i += ((NI) 1);
				}
				goto LA23;
				LA27: ;
				{
					parsetoken_108059((&info), token, value, (&j));
					token = copyString(((NimStringDesc*) &TMP167));
				}
				LA23: ;
			}
			break;
			}
		}
	} LA2: ;
	LOC30 = 0;
	LOC30 = timeinfototime_105847((&info));
	memset((void*)(&LOC31), 0, sizeof(LOC31));
	LOC31.Sup.m_type = (&NTI105804);
	getlocaltime_105841(LOC30, (&LOC31));
	info.weekday = LOC31.weekday;
	genericAssign((void*)Result, (void*)(&info), (&NTI105804));
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, countleapyears_109038)(NI yearspan) {
	NI result;
	NF LOC1;
	NF LOC2;
	NF LOC3;
	result = 0;
	LOC1 = 0;
	LOC1 = HEX2F_88438((NI)(yearspan - ((NI) 1)), ((NI) 4));
	LOC2 = 0;
	LOC2 = HEX2F_88438((NI)(yearspan - ((NI) 1)), ((NI) 100));
	LOC3 = 0;
	LOC3 = HEX2F_88438((NI)(yearspan - ((NI) 1)), ((NI) 400));
	result = ((NI) (((NF)(((NF)(LOC1) - (NF)(LOC2))) + (NF)(LOC3))));
	return result;
}

N_NIMCALL(NI, countdays_109045)(NI yearspan) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = countleapyears_109038(yearspan);
	result = (NI)((NI)((NI)(yearspan - ((NI) 1)) * ((NI) 365)) + LOC1);
	return result;
}

N_NIMCALL(NI, countyears_109050)(NI dayspan) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = countleapyears_109038((NI)(dayspan / ((NI) 365)));
	result = (NI)((NI)(dayspan - LOC1) / ((NI) 365));
	return result;
}

N_NIMCALL(TY109059, countyearsanddays_109056)(NI dayspan) {
	TY109059 result;
	NI days;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = 0;
	LOC1 = countleapyears_109038((NI)(dayspan / ((NI) 365)));
	days = (NI)(dayspan - LOC1);
	result.Field0 = (NI)(days / ((NI) 365));
	result.Field1 = ((NI) ((NI)(days % ((NI) 365))));
	return result;
}

N_NIMCALL(NU8, getdayofweek_109076)(NI day, NI month, NI year) {
	NU8 result;
	NI a;
	NI y;
	NI m;
	NI d;
{	result = 0;
	a = (NI)((NI)(((NI) 14) - month) / ((NI) 12));
	y = (NI)(year - a);
	m = (NI)((NI)(month + (NI)(((NI) 12) * a)) - ((NI) 2));
	d = (NI)((NI)((NI)((NI)((NI)((NI)(day + y) + (NI)(y / ((NI) 4))) - (NI)(y / ((NI) 100))) + (NI)(y / ((NI) 400))) + (NI)((NI)(((NI) 31) * m) / ((NI) 12))) % ((NI) 7));
	{
		if (!(((NI) (d)) == ((NI) 0))) goto LA3;
		result = ((NU8) 6);
		goto BeforeRet;
	}
	LA3: ;
	result = ((NU8) ((NI)(((NI) (d)) - ((NI) 1))));
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NU8, getdayofweekjulian_109091)(NI day, NI month, NI year) {
	NU8 result;
	NI a;
	NI y;
	NI m;
	NI d;
	result = 0;
	a = (NI)((NI)(((NI) 14) - month) / ((NI) 12));
	y = (NI)(year - a);
	m = (NI)((NI)(month + (NI)(((NI) 12) * a)) - ((NI) 2));
	d = (NI)((NI)((NI)((NI)((NI)(((NI) 5) + day) + y) + (NI)(y / ((NI) 4))) + (NI)((NI)(((NI) 31) * m) / ((NI) 12))) % ((NI) 7));
	result = ((NU8) (d));
	return result;
}

N_NIMCALL(void, timetotimeinfo_109102)(time_t t, Timeinfo105804* Result) {
	NI secs;
	NF LOC1;
	NI dayssinceepoch;
	TY109059 LOC2;
	NI yearssinceepoch;
	NI daysremaining;
	NI dayseconds;
	NI y;
	NU8 mon;
	NI days;
	NI daysinmonth;
	NI yd;
	NU8 m;
	NI md;
	NU8 wd;
	NI h;
	NI mi;
	NI s;
	Timeinfo105804 LOC7;
	LOC1 = 0;
	LOC1 = toseconds_105858(t);
	secs = ((NI) (LOC1));
	dayssinceepoch = (NI)(secs / ((NI) 86400));
	LOC2 = countyearsanddays_109056(dayssinceepoch);
	yearssinceepoch = LOC2.Field0;
	daysremaining = LOC2.Field1;
	dayseconds = (NI)(secs % ((NI) 86400));
	y = (NI)(yearssinceepoch + ((NI) 1970));
	mon = ((NU8) 0);
	days = daysremaining;
	daysinmonth = getdaysinmonth_106114(mon, y);
	{
		while (1) {
			NIM_BOOL LOC5;
			LOC5 = 0;
			LOC5 = (daysinmonth < days);
			if (!(LOC5)) goto LA6;
			LOC5 = (mon <= ((NU8) 11));
			LA6: ;
			if (!LOC5) goto LA4;
			days -= daysinmonth;
			mon += ((NI) 1);
			daysinmonth = getdaysinmonth_106114(mon, y);
		} LA4: ;
	}
	yd = daysremaining;
	m = mon;
	md = days;
	wd = getdayofweek_109076(days, (NI)(((NI) (mon)) + ((NI) 1)), y);
	h = (NI)(((NI) ((NI)(((NI) (dayseconds)) / ((NI) 3600)))) + ((NI) 1));
	mi = (NI)(((NI) ((NI)(((NI) (dayseconds)) % ((NI) 3600)))) / ((NI) 60));
	s = (NI)(((NI) (dayseconds)) % ((NI) 60));
	memset((void*)(&LOC7), 0, sizeof(LOC7));
	LOC7.Sup.m_type = (&NTI105804);
	memset((void*)(&LOC7), 0, sizeof(LOC7));
	LOC7.Sup.m_type = (&NTI105804);
	LOC7.year = y;
	LOC7.yearday = ((NI) (yd));
	LOC7.month = m;
	LOC7.monthday = ((NI) (md));
	LOC7.weekday = wd;
	LOC7.hour = ((NI) (h));
	LOC7.minute = ((NI) (mi));
	LOC7.second = ((NI) (s));
	genericShallowAssign((void*)Result, (void*)(&LOC7), (&NTI105804));
}

N_NIMCALL(Timeinterval105806, timetotimeinterval_109160)(time_t t) {
	Timeinterval105806 result;
	NI secs;
	NF LOC1;
	NI dayssinceepoch;
	TY109059 LOC2;
	NI yearssinceepoch;
	NI daysremaining;
	NI dayseconds;
	NU8 mon;
	NI days;
	NI daysinmonth;
	memset((void*)(&result), 0, sizeof(result));
	LOC1 = 0;
	LOC1 = toseconds_105858(t);
	secs = ((NI) (LOC1));
	dayssinceepoch = (NI)(secs / ((NI) 86400));
	LOC2 = countyearsanddays_109056(dayssinceepoch);
	yearssinceepoch = LOC2.Field0;
	daysremaining = LOC2.Field1;
	dayseconds = (NI)(secs % ((NI) 86400));
	result.years = (NI)(yearssinceepoch + ((NI) 1970));
	mon = ((NU8) 0);
	days = daysremaining;
	daysinmonth = getdaysinmonth_106114(mon, result.years);
	{
		while (1) {
			NIM_BOOL LOC5;
			LOC5 = 0;
			LOC5 = (daysinmonth < days);
			if (!(LOC5)) goto LA6;
			LOC5 = (mon <= ((NU8) 11));
			LA6: ;
			if (!LOC5) goto LA4;
			days -= daysinmonth;
			mon += ((NI) 1);
			daysinmonth = getdaysinmonth_106114(mon, result.years);
		} LA4: ;
	}
	result.months = (NI)(((NI) (mon)) + ((NI) 1));
	result.days = days;
	result.hours = ((NI) ((NI)(((NI) ((NI)(((NI) (dayseconds)) / ((NI) 3600)))) + ((NI) 1))));
	result.minutes = ((NI) ((NI)(((NI) ((NI)(((NI) (dayseconds)) % ((NI) 3600)))) / ((NI) 60))));
	result.seconds = ((NI) ((NI)(((NI) (dayseconds)) % ((NI) 60))));
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void) {
	tzset();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void) {
static TNimNode* TMP159[11];
static TNimNode* TMP160[12];
NI TMP162;
static char* NIM_CONST TMP161[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP163[7];
NI TMP165;
static char* NIM_CONST TMP164[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP157[33];
NTI105804.size = sizeof(Timeinfo105804);
NTI105804.kind = 17;
NTI105804.base = (&NTI3608);
TMP159[0] = &TMP157[1];
NTI105807.size = sizeof(NI);
NTI105807.kind = 20;
NTI105807.base = (&NTI104);
NTI105807.flags = 3;
TMP157[1].kind = 1;
TMP157[1].offset = offsetof(Timeinfo105804, second);
TMP157[1].typ = (&NTI105807);
TMP157[1].name = "second";
TMP159[1] = &TMP157[2];
NTI105810.size = sizeof(NI);
NTI105810.kind = 20;
NTI105810.base = (&NTI104);
NTI105810.flags = 3;
TMP157[2].kind = 1;
TMP157[2].offset = offsetof(Timeinfo105804, minute);
TMP157[2].typ = (&NTI105810);
TMP157[2].name = "minute";
TMP159[2] = &TMP157[3];
NTI105812.size = sizeof(NI);
NTI105812.kind = 20;
NTI105812.base = (&NTI104);
NTI105812.flags = 3;
TMP157[3].kind = 1;
TMP157[3].offset = offsetof(Timeinfo105804, hour);
TMP157[3].typ = (&NTI105812);
TMP157[3].name = "hour";
TMP159[3] = &TMP157[4];
NTI105815.size = sizeof(NI);
NTI105815.kind = 20;
NTI105815.base = (&NTI104);
NTI105815.flags = 3;
TMP157[4].kind = 1;
TMP157[4].offset = offsetof(Timeinfo105804, monthday);
TMP157[4].typ = (&NTI105815);
TMP157[4].name = "monthday";
TMP159[4] = &TMP157[5];
NTI105603.size = sizeof(NU8);
NTI105603.kind = 14;
NTI105603.base = 0;
NTI105603.flags = 3;
for (TMP162 = 0; TMP162 < 12; TMP162++) {
TMP157[TMP162+6].kind = 1;
TMP157[TMP162+6].offset = TMP162;
TMP157[TMP162+6].name = TMP161[TMP162];
TMP160[TMP162] = &TMP157[TMP162+6];
}
TMP157[18].len = 12; TMP157[18].kind = 2; TMP157[18].sons = &TMP160[0];
NTI105603.node = &TMP157[18];
TMP157[5].kind = 1;
TMP157[5].offset = offsetof(Timeinfo105804, month);
TMP157[5].typ = (&NTI105603);
TMP157[5].name = "month";
TMP159[5] = &TMP157[19];
TMP157[19].kind = 1;
TMP157[19].offset = offsetof(Timeinfo105804, year);
TMP157[19].typ = (&NTI104);
TMP157[19].name = "year";
TMP159[6] = &TMP157[20];
NTI105605.size = sizeof(NU8);
NTI105605.kind = 14;
NTI105605.base = 0;
NTI105605.flags = 3;
for (TMP165 = 0; TMP165 < 7; TMP165++) {
TMP157[TMP165+21].kind = 1;
TMP157[TMP165+21].offset = TMP165;
TMP157[TMP165+21].name = TMP164[TMP165];
TMP163[TMP165] = &TMP157[TMP165+21];
}
TMP157[28].len = 7; TMP157[28].kind = 2; TMP157[28].sons = &TMP163[0];
NTI105605.node = &TMP157[28];
TMP157[20].kind = 1;
TMP157[20].offset = offsetof(Timeinfo105804, weekday);
TMP157[20].typ = (&NTI105605);
TMP157[20].name = "weekday";
TMP159[7] = &TMP157[29];
NTI105821.size = sizeof(NI);
NTI105821.kind = 20;
NTI105821.base = (&NTI104);
NTI105821.flags = 3;
TMP157[29].kind = 1;
TMP157[29].offset = offsetof(Timeinfo105804, yearday);
TMP157[29].typ = (&NTI105821);
TMP157[29].name = "yearday";
TMP159[8] = &TMP157[30];
TMP157[30].kind = 1;
TMP157[30].offset = offsetof(Timeinfo105804, isdst);
TMP157[30].typ = (&NTI130);
TMP157[30].name = "isDST";
TMP159[9] = &TMP157[31];
TMP157[31].kind = 1;
TMP157[31].offset = offsetof(Timeinfo105804, tzname);
TMP157[31].typ = (&NTI138);
TMP157[31].name = "tzname";
TMP159[10] = &TMP157[32];
TMP157[32].kind = 1;
TMP157[32].offset = offsetof(Timeinfo105804, timezone);
TMP157[32].typ = (&NTI104);
TMP157[32].name = "timezone";
TMP157[0].len = 11; TMP157[0].kind = 2; TMP157[0].sons = &TMP159[0];
NTI105804.node = &TMP157[0];
}

