/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/tamura/.choosenim/toolchains/nim-0.13.0/lib -o /home/tamura/project/atcoder/src/nimcache/stdlib_math.o /home/tamura/project/atcoder/src/nimcache/stdlib_math.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY122401 TY122401;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY122401 {
NI Field0;
NI Field1;
};
N_NIMCALL(NI, binom_104202)(NI n, NI k);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, fac_104226)(NI n);
N_NIMCALL(NU8, classify_110217)(NF x);
N_NIMCALL(NIM_BOOL, ispoweroftwo_110223)(NI x);
N_NIMCALL(NI, nextpoweroftwo_110227)(NI x);
N_NIMCALL(NI, countbits32_110819)(NI32 n);
N_NIMCALL(NF, log2_111016)(NF x);
N_NIMCALL(NF, random_110873)(NF max);
N_NIMCALL(void, randomize_110876)(void);
N_NIMCALL(void, randomize_111001)(NI seed);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI, random_110870)(NI max);
N_NIMCALL(NF, mod_112217)(NF x, NF y);
N_NIMCALL(NI, toint_122214)(NI a);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(NI, tofin_122206)(NI a);
N_NIMCALL(void, HEX2AHEX3D_122250)(NI* a, NI b);
STRING_LITERAL(TMP330, "\012  0 <= y ", 10);
extern TFrame* frameptr_19436;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(NI, binom_104202)(NI n, NI k) {
	NI result;
	nimfr("binom", "math.nim")
{	result = 0;
	nimln(26, "math.nim");
	{
		if (!(k <= ((NI) 0))) goto LA3;
		result = ((NI) 1);
		goto BeforeRet;
	}
	LA3: ;
	nimln(27, "math.nim");
	{
		NI TMP148;
		NI TMP149;
		nimln(357, "system.nim");
		nimln(27, "math.nim");
		TMP148 = mulInt(((NI) 2), k);
		if (!(n < (NI)(TMP148))) goto LA7;
		TMP149 = subInt(n, k);
		result = binom_104202(n, (NI)(TMP149));
		goto BeforeRet;
	}
	LA7: ;
	nimln(28, "math.nim");
	result = n;
	{
		NI i_104218;
		NI res_104222;
		i_104218 = 0;
		nimln(1874, "system.nim");
		res_104222 = ((NI) 2);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP150;
				NI TMP151;
				NI TMP152;
				NI TMP153;
				NI TMP154;
				if (!(res_104222 <= k)) goto LA11;
				nimln(1876, "system.nim");
				i_104218 = res_104222;
				nimln(30, "math.nim");
				TMP150 = addInt(n, ((NI) 1));
				TMP151 = subInt((NI)(TMP150), i_104218);
				TMP152 = mulInt(result, (NI)(TMP151));
				TMP153 = divInt((NI)(TMP152), i_104218);
				result = (NI)(TMP153);
				nimln(1890, "system.nim");
				TMP154 = addInt(res_104222, ((NI) 1));
				res_104222 = (NI)(TMP154);
			} LA11: ;
		}
	}
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, fac_104226)(NI n) {
	NI result;
	nimfr("fac", "math.nim")
	result = 0;
	nimln(34, "math.nim");
	result = ((NI) 1);
	{
		NI i_104241;
		NI res_104245;
		i_104241 = 0;
		nimln(1874, "system.nim");
		res_104245 = ((NI) 2);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP155;
				NI TMP156;
				if (!(res_104245 <= n)) goto LA3;
				nimln(1876, "system.nim");
				i_104241 = res_104245;
				nimln(36, "math.nim");
				TMP155 = mulInt(result, i_104241);
				result = (NI)(TMP155);
				nimln(1890, "system.nim");
				TMP156 = addInt(res_104245, ((NI) 1));
				res_104245 = (NI)(TMP156);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NU8, classify_110217)(NF x) {
	NU8 result;
{	result = 0;
	{
		if (!(x == 0.0)) goto LA3;
		{
			if (!(((NF)(1.0000000000000000e+00) / (NF)(x)) == INF)) goto LA7;
			result = ((NU8) 2);
			goto BeforeRet;
		}
		goto LA5;
		LA7: ;
		{
			result = ((NU8) 3);
			goto BeforeRet;
		}
		LA5: ;
	}
	LA3: ;
	{
		if (!(((NF)(x) * (NF)(5.0000000000000000e-01)) == x)) goto LA12;
		{
			if (!(0.0 < x)) goto LA16;
			result = ((NU8) 5);
			goto BeforeRet;
		}
		goto LA14;
		LA16: ;
		{
			result = ((NU8) 6);
			goto BeforeRet;
		}
		LA14: ;
	}
	LA12: ;
	{
		if (!!((x == x))) goto LA21;
		result = ((NU8) 4);
		goto BeforeRet;
	}
	LA21: ;
	result = ((NU8) 0);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, ispoweroftwo_110223)(NI x) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = (((NI) 0) < x);
	if (!(LOC1)) goto LA2;
	LOC1 = ((NI)(x & (NI)(x - ((NI) 1))) == ((NI) 0));
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, nextpoweroftwo_110227)(NI x) {
	NI result;
	result = 0;
	result = (NI)(x - ((NI) 1));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 32))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 16))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 8))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 4))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 2))));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(((NI) 1))));
	result += ((NI) ((NI)(((NI) 1) + ((NI) ((x <= ((NI) 0)))))));
	return result;
}

N_NIMCALL(NI, countbits32_110819)(NI32 n) {
	NI result;
	NI32 v;
	result = 0;
	v = n;
	v = (NI32)((NU32)(v) - (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 1))) & ((NI32) 1431655765))));
	v = (NI32)((NU32)((NI32)(v & ((NI32) 858993459))) + (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 2))) & ((NI32) 858993459))));
	result = ((NI) ((NI32)((NU32)((NI32)((NU32)((NI32)((NI32)((NU32)(v) + (NU32)((NI32)((NU32)(v) >> (NU32)(((NI32) 4))))) & ((NI32) 252645135))) * (NU32)(((NI32) 16843009)))) >> (NU32)(((NI32) 24)))));
	return result;
}

N_NIMCALL(NF, log2_111016)(NF x) {
	NF result;
	NF LOC1;
	NF LOC2;
{	result = 0;
	LOC1 = 0;
	LOC1 = log(x);
	LOC2 = 0;
	LOC2 = log(2.0000000000000000e+00);
	result = ((NF)(LOC1) / (NF)(LOC2));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NF, random_110873)(NF max) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = drand48();
	result = ((NF)(LOC1) * (NF)(max));
	return result;
}

N_NIMCALL(void, randomize_111001)(NI seed) {
	srand(((int) (seed)));
	srand48(seed);
}

N_NIMCALL(void, randomize_110876)(void) {
	union { NF source; NI dest; } LOC1;
	LOC1.source = ntepochTime();
	randomize_111001(LOC1.dest);
}

N_NIMCALL(NI, random_110870)(NI max) {
	NI result;
	int LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = rand();
	result = (NI)(((NI) (LOC1)) % max);
	return result;
}

N_NIMCALL(NF, mod_112217)(NF x, NF y) {
	NF result;
	result = 0;
	{
		if (!(y == 0.0)) goto LA3;
		result = x;
	}
	goto LA1;
	LA3: ;
	{
		NF LOC6;
		LOC6 = 0;
		LOC6 = floor(((NF)(x) / (NF)(y)));
		result = ((NF)(x) - (NF)(((NF)(y) * (NF)(LOC6))));
	}
	LA1: ;
	return result;
}

N_NIMCALL(NI, HEX5E_122262)(NI x_122266, NI y_122268) {
	NI result;
	TY122401 LOC6;
	NI x;
	NI y;
	nimfr("^", "math.nim")
	result = 0;
	nimln(365, "math.nim");
	{
		NI LOC3;
		LOC3 = 0;
		LOC3 = toint_122214(y_122268);
		if (!!((((NI) 0) <= LOC3))) goto LA4;
		failedassertimpl_89116(((NimStringDesc*) &TMP330));
	}
	LA4: ;
	nimln(366, "math.nim");
	LOC6.Field0 = x_122266;
	LOC6.Field1 = y_122268;
	x = LOC6.Field0;
	y = LOC6.Field1;
	nimln(367, "math.nim");
	result = tofin_122206(((NI) 1));
	{
		nimln(369, "math.nim");
		while (1) {
			NI LOC14;
			nimln(370, "math.nim");
			{
				NI LOC11;
				nimln(349, "system.nim");
				nimln(370, "math.nim");
				LOC11 = 0;
				LOC11 = toint_122214(y);
				if (!!((((NI) ((NI)(LOC11 & ((NI) 1)))) == ((NI) 0)))) goto LA12;
				nimln(371, "math.nim");
				HEX2AHEX3D_122250((&result), x);
			}
			LA12: ;
			nimln(372, "math.nim");
			LOC14 = 0;
			LOC14 = toint_122214(y);
			y = tofin_122206((NI)((NU64)(LOC14) >> (NU64)(((NI) 1))));
			nimln(373, "math.nim");
			{
				NI LOC17;
				LOC17 = 0;
				LOC17 = toint_122214(y);
				if (!(LOC17 == ((NI) 0))) goto LA18;
				nimln(374, "math.nim");
				goto LA7;
			}
			LA18: ;
			nimln(375, "math.nim");
			HEX2AHEX3D_122250((&x), x);
		}
	} LA7: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void) {
	nimfr("math", "math.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void) {
}

