(define n (read))
(define x (div (* n (+ n 1) 2)))
(define a (make-vector n 0))
(dotimes (i n) (vector-set! a i (read)))
(define g (make-tree-map = <))
(dotimes (i n)
  (let* ((key (vector-ref a i)))
    (tree-map-put! g key (+ 1 (tree-map-get g key 0)))
  )
)
