[[testcase]]
in = """
2 1 1
cc
"""
out = """
No
No
"""

[[testcase]]
in = """
2 1 1
aa
"""
out = """
Yes
Yes
"""

[[testcase]]
in = """
2 1 1
bb
"""
out = """
Yes
No
"""

[[testcase]]
in = """
2 1 1
ab
"""
out = """
Yes
Yes
"""

[[testcase]]
in = """
3 2 1
bbb
"""
out = """
Yes
No
No
"""

[[testcase]]
in = """
4 3 1
abba
"""
out = """
Yes
Yes
No
Yes
"""

[[testcase]]
in = """
6 3 1
abbaaa
"""
out = """
Yes
Yes
No
Yes
Yes
No
"""
